/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class InvoiceInvoiceState.
* @enum {}
* @readonly
*/
export default class InvoiceInvoiceState {
    
        /**
         * value: "OPEN"
         * @const
         */
        "OPEN" = "OPEN";

    
        /**
         * value: "SETTLED"
         * @const
         */
        "SETTLED" = "SETTLED";

    
        /**
         * value: "CANCELED"
         * @const
         */
        "CANCELED" = "CANCELED";

    
        /**
         * value: "ACCEPTED"
         * @const
         */
        "ACCEPTED" = "ACCEPTED";

    

    /**
    * Returns a <code>InvoiceInvoiceState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/InvoiceInvoiceState} The enum <code>InvoiceInvoiceState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

