/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcDebugLevelResponse model module.
 * @module model/LnrpcDebugLevelResponse
 * @version version not set
 */
class LnrpcDebugLevelResponse {
    /**
     * Constructs a new <code>LnrpcDebugLevelResponse</code>.
     * @alias module:model/LnrpcDebugLevelResponse
     */
    constructor() { 
        LnrpcDebugLevelResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcDebugLevelResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcDebugLevelResponse} obj Optional instance to populate.
     * @return {module:model/LnrpcDebugLevelResponse} The populated <code>LnrpcDebugLevelResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcDebugLevelResponse();

            if (data.hasOwnProperty('sub_systems')) {
                obj['sub_systems'] = ApiClient.convertToType(data['sub_systems'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} sub_systems
 */
LnrpcDebugLevelResponse.prototype['sub_systems'] = undefined;






export default LnrpcDebugLevelResponse;

