/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcChanPointShim from './LnrpcChanPointShim';
import LnrpcPsbtShim from './LnrpcPsbtShim';

/**
 * The LnrpcFundingShim model module.
 * @module model/LnrpcFundingShim
 * @version version not set
 */
class LnrpcFundingShim {
    /**
     * Constructs a new <code>LnrpcFundingShim</code>.
     * @alias module:model/LnrpcFundingShim
     */
    constructor() { 
        LnrpcFundingShim.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcFundingShim</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcFundingShim} obj Optional instance to populate.
     * @return {module:model/LnrpcFundingShim} The populated <code>LnrpcFundingShim</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcFundingShim();

            if (data.hasOwnProperty('chan_point_shim')) {
                obj['chan_point_shim'] = LnrpcChanPointShim.constructFromObject(data['chan_point_shim']);
            }
            if (data.hasOwnProperty('psbt_shim')) {
                obj['psbt_shim'] = LnrpcPsbtShim.constructFromObject(data['psbt_shim']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LnrpcChanPointShim} chan_point_shim
 */
LnrpcFundingShim.prototype['chan_point_shim'] = undefined;

/**
 * @member {module:model/LnrpcPsbtShim} psbt_shim
 */
LnrpcFundingShim.prototype['psbt_shim'] = undefined;






export default LnrpcFundingShim;

