/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LnrpcCommitmentType.
* @enum {}
* @readonly
*/
export default class LnrpcCommitmentType {
    
        /**
         * value: "LEGACY"
         * @const
         */
        "LEGACY" = "LEGACY";

    
        /**
         * value: "STATIC_REMOTE_KEY"
         * @const
         */
        "STATIC_REMOTE_KEY" = "STATIC_REMOTE_KEY";

    
        /**
         * value: "ANCHORS"
         * @const
         */
        "ANCHORS" = "ANCHORS";

    
        /**
         * value: "UNKNOWN_COMMITMENT_TYPE"
         * @const
         */
        "UNKNOWN_COMMITMENT_TYPE" = "UNKNOWN_COMMITMENT_TYPE";

    

    /**
    * Returns a <code>LnrpcCommitmentType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LnrpcCommitmentType} The enum <code>LnrpcCommitmentType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

