/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LnrpcPaymentFailureReason.
* @enum {}
* @readonly
*/
export default class LnrpcPaymentFailureReason {
    
        /**
         * value: "FAILURE_REASON_NONE"
         * @const
         */
        "NONE" = "FAILURE_REASON_NONE";

    
        /**
         * value: "FAILURE_REASON_TIMEOUT"
         * @const
         */
        "TIMEOUT" = "FAILURE_REASON_TIMEOUT";

    
        /**
         * value: "FAILURE_REASON_NO_ROUTE"
         * @const
         */
        "NO_ROUTE" = "FAILURE_REASON_NO_ROUTE";

    
        /**
         * value: "FAILURE_REASON_ERROR"
         * @const
         */
        "ERROR" = "FAILURE_REASON_ERROR";

    
        /**
         * value: "FAILURE_REASON_INCORRECT_PAYMENT_DETAILS"
         * @const
         */
        "INCORRECT_PAYMENT_DETAILS" = "FAILURE_REASON_INCORRECT_PAYMENT_DETAILS";

    
        /**
         * value: "FAILURE_REASON_INSUFFICIENT_BALANCE"
         * @const
         */
        "INSUFFICIENT_BALANCE" = "FAILURE_REASON_INSUFFICIENT_BALANCE";

    

    /**
    * Returns a <code>LnrpcPaymentFailureReason</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LnrpcPaymentFailureReason} The enum <code>LnrpcPaymentFailureReason</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

