/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcSignMessageRequest model module.
 * @module model/LnrpcSignMessageRequest
 * @version version not set
 */
class LnrpcSignMessageRequest {
    /**
     * Constructs a new <code>LnrpcSignMessageRequest</code>.
     * @alias module:model/LnrpcSignMessageRequest
     */
    constructor() { 
        LnrpcSignMessageRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcSignMessageRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcSignMessageRequest} obj Optional instance to populate.
     * @return {module:model/LnrpcSignMessageRequest} The populated <code>LnrpcSignMessageRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcSignMessageRequest();

            if (data.hasOwnProperty('msg')) {
                obj['msg'] = ApiClient.convertToType(data['msg'], 'Blob');
            }
        }
        return obj;
    }


}

/**
 * The message to be signed. When using REST, this field must be encoded as base64.
 * @member {Blob} msg
 */
LnrpcSignMessageRequest.prototype['msg'] = undefined;






export default LnrpcSignMessageRequest;

