/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcInvoice from './LnrpcInvoice';

/**
 * The LnrpcListInvoiceResponse model module.
 * @module model/LnrpcListInvoiceResponse
 * @version version not set
 */
class LnrpcListInvoiceResponse {
    /**
     * Constructs a new <code>LnrpcListInvoiceResponse</code>.
     * @alias module:model/LnrpcListInvoiceResponse
     */
    constructor() { 
        LnrpcListInvoiceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcListInvoiceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcListInvoiceResponse} obj Optional instance to populate.
     * @return {module:model/LnrpcListInvoiceResponse} The populated <code>LnrpcListInvoiceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcListInvoiceResponse();

            if (data.hasOwnProperty('invoices')) {
                obj['invoices'] = ApiClient.convertToType(data['invoices'], [LnrpcInvoice]);
            }
            if (data.hasOwnProperty('last_index_offset')) {
                obj['last_index_offset'] = ApiClient.convertToType(data['last_index_offset'], 'String');
            }
            if (data.hasOwnProperty('first_index_offset')) {
                obj['first_index_offset'] = ApiClient.convertToType(data['first_index_offset'], 'String');
            }
        }
        return obj;
    }


}

/**
 * A list of invoices from the time slice of the time series specified in the request.
 * @member {Array.<module:model/LnrpcInvoice>} invoices
 */
LnrpcListInvoiceResponse.prototype['invoices'] = undefined;

/**
 * The index of the last item in the set of returned invoices. This can be used to seek further, pagination style.
 * @member {String} last_index_offset
 */
LnrpcListInvoiceResponse.prototype['last_index_offset'] = undefined;

/**
 * The index of the last item in the set of returned invoices. This can be used to seek backwards, pagination style.
 * @member {String} first_index_offset
 */
LnrpcListInvoiceResponse.prototype['first_index_offset'] = undefined;






export default LnrpcListInvoiceResponse;

