/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcChannelCloseUpdate model module.
 * @module model/LnrpcChannelCloseUpdate
 * @version version not set
 */
class LnrpcChannelCloseUpdate {
    /**
     * Constructs a new <code>LnrpcChannelCloseUpdate</code>.
     * @alias module:model/LnrpcChannelCloseUpdate
     */
    constructor() { 
        LnrpcChannelCloseUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcChannelCloseUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcChannelCloseUpdate} obj Optional instance to populate.
     * @return {module:model/LnrpcChannelCloseUpdate} The populated <code>LnrpcChannelCloseUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcChannelCloseUpdate();

            if (data.hasOwnProperty('closing_txid')) {
                obj['closing_txid'] = ApiClient.convertToType(data['closing_txid'], 'Blob');
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Blob} closing_txid
 */
LnrpcChannelCloseUpdate.prototype['closing_txid'] = undefined;

/**
 * @member {Boolean} success
 */
LnrpcChannelCloseUpdate.prototype['success'] = undefined;






export default LnrpcChannelCloseUpdate;

