/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcLightningAddress model module.
 * @module model/LnrpcLightningAddress
 * @version version not set
 */
class LnrpcLightningAddress {
    /**
     * Constructs a new <code>LnrpcLightningAddress</code>.
     * @alias module:model/LnrpcLightningAddress
     */
    constructor() { 
        LnrpcLightningAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcLightningAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcLightningAddress} obj Optional instance to populate.
     * @return {module:model/LnrpcLightningAddress} The populated <code>LnrpcLightningAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcLightningAddress();

            if (data.hasOwnProperty('pubkey')) {
                obj['pubkey'] = ApiClient.convertToType(data['pubkey'], 'String');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} pubkey
 */
LnrpcLightningAddress.prototype['pubkey'] = undefined;

/**
 * @member {String} host
 */
LnrpcLightningAddress.prototype['host'] = undefined;






export default LnrpcLightningAddress;

