/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LnrpcResolutionType.
* @enum {}
* @readonly
*/
export default class LnrpcResolutionType {
    
        /**
         * value: "TYPE_UNKNOWN"
         * @const
         */
        "TYPE_UNKNOWN" = "TYPE_UNKNOWN";

    
        /**
         * value: "ANCHOR"
         * @const
         */
        "ANCHOR" = "ANCHOR";

    
        /**
         * value: "INCOMING_HTLC"
         * @const
         */
        "INCOMING_HTLC" = "INCOMING_HTLC";

    
        /**
         * value: "OUTGOING_HTLC"
         * @const
         */
        "OUTGOING_HTLC" = "OUTGOING_HTLC";

    
        /**
         * value: "COMMIT"
         * @const
         */
        "COMMIT" = "COMMIT";

    

    /**
    * Returns a <code>LnrpcResolutionType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LnrpcResolutionType} The enum <code>LnrpcResolutionType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

