/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcDeleteMacaroonIDResponse model module.
 * @module model/LnrpcDeleteMacaroonIDResponse
 * @version version not set
 */
class LnrpcDeleteMacaroonIDResponse {
    /**
     * Constructs a new <code>LnrpcDeleteMacaroonIDResponse</code>.
     * @alias module:model/LnrpcDeleteMacaroonIDResponse
     */
    constructor() { 
        LnrpcDeleteMacaroonIDResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcDeleteMacaroonIDResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcDeleteMacaroonIDResponse} obj Optional instance to populate.
     * @return {module:model/LnrpcDeleteMacaroonIDResponse} The populated <code>LnrpcDeleteMacaroonIDResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcDeleteMacaroonIDResponse();

            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * A boolean indicates that the deletion is successful.
 * @member {Boolean} deleted
 */
LnrpcDeleteMacaroonIDResponse.prototype['deleted'] = undefined;






export default LnrpcDeleteMacaroonIDResponse;

