/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LnrpcAddressType.
* @enum {}
* @readonly
*/
export default class LnrpcAddressType {
    
        /**
         * value: "WITNESS_PUBKEY_HASH"
         * @const
         */
        "WITNESS_PUBKEY_HASH" = "WITNESS_PUBKEY_HASH";

    
        /**
         * value: "NESTED_PUBKEY_HASH"
         * @const
         */
        "NESTED_PUBKEY_HASH" = "NESTED_PUBKEY_HASH";

    
        /**
         * value: "UNUSED_WITNESS_PUBKEY_HASH"
         * @const
         */
        "UNUSED_WITNESS_PUBKEY_HASH" = "UNUSED_WITNESS_PUBKEY_HASH";

    
        /**
         * value: "UNUSED_NESTED_PUBKEY_HASH"
         * @const
         */
        "UNUSED_NESTED_PUBKEY_HASH" = "UNUSED_NESTED_PUBKEY_HASH";

    

    /**
    * Returns a <code>LnrpcAddressType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LnrpcAddressType} The enum <code>LnrpcAddressType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

