/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcSignMessageResponse model module.
 * @module model/LnrpcSignMessageResponse
 * @version version not set
 */
class LnrpcSignMessageResponse {
    /**
     * Constructs a new <code>LnrpcSignMessageResponse</code>.
     * @alias module:model/LnrpcSignMessageResponse
     */
    constructor() { 
        LnrpcSignMessageResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcSignMessageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcSignMessageResponse} obj Optional instance to populate.
     * @return {module:model/LnrpcSignMessageResponse} The populated <code>LnrpcSignMessageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcSignMessageResponse();

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} signature
 */
LnrpcSignMessageResponse.prototype['signature'] = undefined;






export default LnrpcSignMessageResponse;

