/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcFeature from './LnrpcFeature';
import LnrpcRouteHint from './LnrpcRouteHint';

/**
 * The LnrpcPayReq model module.
 * @module model/LnrpcPayReq
 * @version version not set
 */
class LnrpcPayReq {
    /**
     * Constructs a new <code>LnrpcPayReq</code>.
     * @alias module:model/LnrpcPayReq
     */
    constructor() { 
        LnrpcPayReq.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcPayReq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcPayReq} obj Optional instance to populate.
     * @return {module:model/LnrpcPayReq} The populated <code>LnrpcPayReq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcPayReq();

            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], 'String');
            }
            if (data.hasOwnProperty('payment_hash')) {
                obj['payment_hash'] = ApiClient.convertToType(data['payment_hash'], 'String');
            }
            if (data.hasOwnProperty('num_satoshis')) {
                obj['num_satoshis'] = ApiClient.convertToType(data['num_satoshis'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
            if (data.hasOwnProperty('expiry')) {
                obj['expiry'] = ApiClient.convertToType(data['expiry'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('description_hash')) {
                obj['description_hash'] = ApiClient.convertToType(data['description_hash'], 'String');
            }
            if (data.hasOwnProperty('fallback_addr')) {
                obj['fallback_addr'] = ApiClient.convertToType(data['fallback_addr'], 'String');
            }
            if (data.hasOwnProperty('cltv_expiry')) {
                obj['cltv_expiry'] = ApiClient.convertToType(data['cltv_expiry'], 'String');
            }
            if (data.hasOwnProperty('route_hints')) {
                obj['route_hints'] = ApiClient.convertToType(data['route_hints'], [LnrpcRouteHint]);
            }
            if (data.hasOwnProperty('payment_addr')) {
                obj['payment_addr'] = ApiClient.convertToType(data['payment_addr'], 'Blob');
            }
            if (data.hasOwnProperty('num_msat')) {
                obj['num_msat'] = ApiClient.convertToType(data['num_msat'], 'String');
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = ApiClient.convertToType(data['features'], {'String': LnrpcFeature});
            }
        }
        return obj;
    }


}

/**
 * @member {String} destination
 */
LnrpcPayReq.prototype['destination'] = undefined;

/**
 * @member {String} payment_hash
 */
LnrpcPayReq.prototype['payment_hash'] = undefined;

/**
 * @member {String} num_satoshis
 */
LnrpcPayReq.prototype['num_satoshis'] = undefined;

/**
 * @member {String} timestamp
 */
LnrpcPayReq.prototype['timestamp'] = undefined;

/**
 * @member {String} expiry
 */
LnrpcPayReq.prototype['expiry'] = undefined;

/**
 * @member {String} description
 */
LnrpcPayReq.prototype['description'] = undefined;

/**
 * @member {String} description_hash
 */
LnrpcPayReq.prototype['description_hash'] = undefined;

/**
 * @member {String} fallback_addr
 */
LnrpcPayReq.prototype['fallback_addr'] = undefined;

/**
 * @member {String} cltv_expiry
 */
LnrpcPayReq.prototype['cltv_expiry'] = undefined;

/**
 * @member {Array.<module:model/LnrpcRouteHint>} route_hints
 */
LnrpcPayReq.prototype['route_hints'] = undefined;

/**
 * @member {Blob} payment_addr
 */
LnrpcPayReq.prototype['payment_addr'] = undefined;

/**
 * @member {String} num_msat
 */
LnrpcPayReq.prototype['num_msat'] = undefined;

/**
 * @member {Object.<String, module:model/LnrpcFeature>} features
 */
LnrpcPayReq.prototype['features'] = undefined;






export default LnrpcPayReq;

