/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcChannelBackups from './LnrpcChannelBackups';
import LnrpcMultiChanBackup from './LnrpcMultiChanBackup';

/**
 * The LnrpcChanBackupSnapshot model module.
 * @module model/LnrpcChanBackupSnapshot
 * @version version not set
 */
class LnrpcChanBackupSnapshot {
    /**
     * Constructs a new <code>LnrpcChanBackupSnapshot</code>.
     * @alias module:model/LnrpcChanBackupSnapshot
     */
    constructor() { 
        LnrpcChanBackupSnapshot.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcChanBackupSnapshot</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcChanBackupSnapshot} obj Optional instance to populate.
     * @return {module:model/LnrpcChanBackupSnapshot} The populated <code>LnrpcChanBackupSnapshot</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcChanBackupSnapshot();

            if (data.hasOwnProperty('single_chan_backups')) {
                obj['single_chan_backups'] = LnrpcChannelBackups.constructFromObject(data['single_chan_backups']);
            }
            if (data.hasOwnProperty('multi_chan_backup')) {
                obj['multi_chan_backup'] = LnrpcMultiChanBackup.constructFromObject(data['multi_chan_backup']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LnrpcChannelBackups} single_chan_backups
 */
LnrpcChanBackupSnapshot.prototype['single_chan_backups'] = undefined;

/**
 * @member {module:model/LnrpcMultiChanBackup} multi_chan_backup
 */
LnrpcChanBackupSnapshot.prototype['multi_chan_backup'] = undefined;






export default LnrpcChanBackupSnapshot;

