/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcChannelFeeReport from './LnrpcChannelFeeReport';

/**
 * The LnrpcFeeReportResponse model module.
 * @module model/LnrpcFeeReportResponse
 * @version version not set
 */
class LnrpcFeeReportResponse {
    /**
     * Constructs a new <code>LnrpcFeeReportResponse</code>.
     * @alias module:model/LnrpcFeeReportResponse
     */
    constructor() { 
        LnrpcFeeReportResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcFeeReportResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcFeeReportResponse} obj Optional instance to populate.
     * @return {module:model/LnrpcFeeReportResponse} The populated <code>LnrpcFeeReportResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcFeeReportResponse();

            if (data.hasOwnProperty('channel_fees')) {
                obj['channel_fees'] = ApiClient.convertToType(data['channel_fees'], [LnrpcChannelFeeReport]);
            }
            if (data.hasOwnProperty('day_fee_sum')) {
                obj['day_fee_sum'] = ApiClient.convertToType(data['day_fee_sum'], 'String');
            }
            if (data.hasOwnProperty('week_fee_sum')) {
                obj['week_fee_sum'] = ApiClient.convertToType(data['week_fee_sum'], 'String');
            }
            if (data.hasOwnProperty('month_fee_sum')) {
                obj['month_fee_sum'] = ApiClient.convertToType(data['month_fee_sum'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An array of channel fee reports which describes the current fee schedule for each channel.
 * @member {Array.<module:model/LnrpcChannelFeeReport>} channel_fees
 */
LnrpcFeeReportResponse.prototype['channel_fees'] = undefined;

/**
 * The total amount of fee revenue (in satoshis) the switch has collected over the past 24 hrs.
 * @member {String} day_fee_sum
 */
LnrpcFeeReportResponse.prototype['day_fee_sum'] = undefined;

/**
 * The total amount of fee revenue (in satoshis) the switch has collected over the past 1 week.
 * @member {String} week_fee_sum
 */
LnrpcFeeReportResponse.prototype['week_fee_sum'] = undefined;

/**
 * The total amount of fee revenue (in satoshis) the switch has collected over the past 1 month.
 * @member {String} month_fee_sum
 */
LnrpcFeeReportResponse.prototype['month_fee_sum'] = undefined;






export default LnrpcFeeReportResponse;

