/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LnrpcResolutionOutcome.
* @enum {}
* @readonly
*/
export default class LnrpcResolutionOutcome {
    
        /**
         * value: "OUTCOME_UNKNOWN"
         * @const
         */
        "OUTCOME_UNKNOWN" = "OUTCOME_UNKNOWN";

    
        /**
         * value: "CLAIMED"
         * @const
         */
        "CLAIMED" = "CLAIMED";

    
        /**
         * value: "UNCLAIMED"
         * @const
         */
        "UNCLAIMED" = "UNCLAIMED";

    
        /**
         * value: "ABANDONED"
         * @const
         */
        "ABANDONED" = "ABANDONED";

    
        /**
         * value: "FIRST_STAGE"
         * @const
         */
        "FIRST_STAGE" = "FIRST_STAGE";

    
        /**
         * value: "TIMEOUT"
         * @const
         */
        "TIMEOUT" = "TIMEOUT";

    

    /**
    * Returns a <code>LnrpcResolutionOutcome</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LnrpcResolutionOutcome} The enum <code>LnrpcResolutionOutcome</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

