/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcFundingPsbtFinalize model module.
 * @module model/LnrpcFundingPsbtFinalize
 * @version version not set
 */
class LnrpcFundingPsbtFinalize {
    /**
     * Constructs a new <code>LnrpcFundingPsbtFinalize</code>.
     * @alias module:model/LnrpcFundingPsbtFinalize
     */
    constructor() { 
        LnrpcFundingPsbtFinalize.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcFundingPsbtFinalize</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcFundingPsbtFinalize} obj Optional instance to populate.
     * @return {module:model/LnrpcFundingPsbtFinalize} The populated <code>LnrpcFundingPsbtFinalize</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcFundingPsbtFinalize();

            if (data.hasOwnProperty('signed_psbt')) {
                obj['signed_psbt'] = ApiClient.convertToType(data['signed_psbt'], 'Blob');
            }
            if (data.hasOwnProperty('pending_chan_id')) {
                obj['pending_chan_id'] = ApiClient.convertToType(data['pending_chan_id'], 'Blob');
            }
            if (data.hasOwnProperty('final_raw_tx')) {
                obj['final_raw_tx'] = ApiClient.convertToType(data['final_raw_tx'], 'Blob');
            }
        }
        return obj;
    }


}

/**
 * The funded PSBT that contains all witness data to send the exact channel capacity amount to the PK script returned in the open channel message in a previous step. Cannot be set at the same time as final_raw_tx.
 * @member {Blob} signed_psbt
 */
LnrpcFundingPsbtFinalize.prototype['signed_psbt'] = undefined;

/**
 * The pending channel ID of the channel to get the PSBT for.
 * @member {Blob} pending_chan_id
 */
LnrpcFundingPsbtFinalize.prototype['pending_chan_id'] = undefined;

/**
 * As an alternative to the signed PSBT with all witness data, the final raw wire format transaction can also be specified directly. Cannot be set at the same time as signed_psbt.
 * @member {Blob} final_raw_tx
 */
LnrpcFundingPsbtFinalize.prototype['final_raw_tx'] = undefined;






export default LnrpcFundingPsbtFinalize;

