/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcUtxo from './LnrpcUtxo';

/**
 * The LnrpcListUnspentResponse model module.
 * @module model/LnrpcListUnspentResponse
 * @version version not set
 */
class LnrpcListUnspentResponse {
    /**
     * Constructs a new <code>LnrpcListUnspentResponse</code>.
     * @alias module:model/LnrpcListUnspentResponse
     */
    constructor() { 
        LnrpcListUnspentResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcListUnspentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcListUnspentResponse} obj Optional instance to populate.
     * @return {module:model/LnrpcListUnspentResponse} The populated <code>LnrpcListUnspentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcListUnspentResponse();

            if (data.hasOwnProperty('utxos')) {
                obj['utxos'] = ApiClient.convertToType(data['utxos'], [LnrpcUtxo]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/LnrpcUtxo>} utxos
 */
LnrpcListUnspentResponse.prototype['utxos'] = undefined;






export default LnrpcListUnspentResponse;

