/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcHop from './LnrpcHop';

/**
 * The LnrpcRoute model module.
 * @module model/LnrpcRoute
 * @version version not set
 */
class LnrpcRoute {
    /**
     * Constructs a new <code>LnrpcRoute</code>.
     * A path through the channel graph which runs over one or more channels in succession. This struct carries all the information required to craft the Sphinx onion packet, and send the payment along the first hop in the path. A route is only selected as valid if all the channels have sufficient capacity to carry the initial payment amount after fees are accounted for.
     * @alias module:model/LnrpcRoute
     */
    constructor() { 
        LnrpcRoute.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcRoute</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcRoute} obj Optional instance to populate.
     * @return {module:model/LnrpcRoute} The populated <code>LnrpcRoute</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcRoute();

            if (data.hasOwnProperty('total_time_lock')) {
                obj['total_time_lock'] = ApiClient.convertToType(data['total_time_lock'], 'Number');
            }
            if (data.hasOwnProperty('total_fees')) {
                obj['total_fees'] = ApiClient.convertToType(data['total_fees'], 'String');
            }
            if (data.hasOwnProperty('total_amt')) {
                obj['total_amt'] = ApiClient.convertToType(data['total_amt'], 'String');
            }
            if (data.hasOwnProperty('hops')) {
                obj['hops'] = ApiClient.convertToType(data['hops'], [LnrpcHop]);
            }
            if (data.hasOwnProperty('total_fees_msat')) {
                obj['total_fees_msat'] = ApiClient.convertToType(data['total_fees_msat'], 'String');
            }
            if (data.hasOwnProperty('total_amt_msat')) {
                obj['total_amt_msat'] = ApiClient.convertToType(data['total_amt_msat'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The cumulative (final) time lock across the entire route. This is the CLTV value that should be extended to the first hop in the route. All other hops will decrement the time-lock as advertised, leaving enough time for all hops to wait for or present the payment preimage to complete the payment.
 * @member {Number} total_time_lock
 */
LnrpcRoute.prototype['total_time_lock'] = undefined;

/**
 * The sum of the fees paid at each hop within the final route. In the case of a one-hop payment, this value will be zero as we don't need to pay a fee to ourselves.
 * @member {String} total_fees
 */
LnrpcRoute.prototype['total_fees'] = undefined;

/**
 * The total amount of funds required to complete a payment over this route. This value includes the cumulative fees at each hop. As a result, the HTLC extended to the first-hop in the route will need to have at least this many satoshis, otherwise the route will fail at an intermediate node due to an insufficient amount of fees.
 * @member {String} total_amt
 */
LnrpcRoute.prototype['total_amt'] = undefined;

/**
 * Contains details concerning the specific forwarding details at each hop.
 * @member {Array.<module:model/LnrpcHop>} hops
 */
LnrpcRoute.prototype['hops'] = undefined;

/**
 * The total fees in millisatoshis.
 * @member {String} total_fees_msat
 */
LnrpcRoute.prototype['total_fees_msat'] = undefined;

/**
 * The total amount in millisatoshis.
 * @member {String} total_amt_msat
 */
LnrpcRoute.prototype['total_amt_msat'] = undefined;






export default LnrpcRoute;

