/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcNodeAddress model module.
 * @module model/LnrpcNodeAddress
 * @version version not set
 */
class LnrpcNodeAddress {
    /**
     * Constructs a new <code>LnrpcNodeAddress</code>.
     * @alias module:model/LnrpcNodeAddress
     */
    constructor() { 
        LnrpcNodeAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcNodeAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcNodeAddress} obj Optional instance to populate.
     * @return {module:model/LnrpcNodeAddress} The populated <code>LnrpcNodeAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcNodeAddress();

            if (data.hasOwnProperty('network')) {
                obj['network'] = ApiClient.convertToType(data['network'], 'String');
            }
            if (data.hasOwnProperty('addr')) {
                obj['addr'] = ApiClient.convertToType(data['addr'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} network
 */
LnrpcNodeAddress.prototype['network'] = undefined;

/**
 * @member {String} addr
 */
LnrpcNodeAddress.prototype['addr'] = undefined;






export default LnrpcNodeAddress;

