/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcPayment from './LnrpcPayment';

/**
 * The LnrpcListPaymentsResponse model module.
 * @module model/LnrpcListPaymentsResponse
 * @version version not set
 */
class LnrpcListPaymentsResponse {
    /**
     * Constructs a new <code>LnrpcListPaymentsResponse</code>.
     * @alias module:model/LnrpcListPaymentsResponse
     */
    constructor() { 
        LnrpcListPaymentsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcListPaymentsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcListPaymentsResponse} obj Optional instance to populate.
     * @return {module:model/LnrpcListPaymentsResponse} The populated <code>LnrpcListPaymentsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcListPaymentsResponse();

            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], [LnrpcPayment]);
            }
            if (data.hasOwnProperty('first_index_offset')) {
                obj['first_index_offset'] = ApiClient.convertToType(data['first_index_offset'], 'String');
            }
            if (data.hasOwnProperty('last_index_offset')) {
                obj['last_index_offset'] = ApiClient.convertToType(data['last_index_offset'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/LnrpcPayment>} payments
 */
LnrpcListPaymentsResponse.prototype['payments'] = undefined;

/**
 * The index of the first item in the set of returned payments. This can be used as the index_offset to continue seeking backwards in the next request.
 * @member {String} first_index_offset
 */
LnrpcListPaymentsResponse.prototype['first_index_offset'] = undefined;

/**
 * The index of the last item in the set of returned payments. This can be used as the index_offset to continue seeking forwards in the next request.
 * @member {String} last_index_offset
 */
LnrpcListPaymentsResponse.prototype['last_index_offset'] = undefined;






export default LnrpcListPaymentsResponse;

