/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LnrpcHopHint model module.
 * @module model/LnrpcHopHint
 * @version version not set
 */
class LnrpcHopHint {
    /**
     * Constructs a new <code>LnrpcHopHint</code>.
     * @alias module:model/LnrpcHopHint
     */
    constructor() { 
        LnrpcHopHint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcHopHint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcHopHint} obj Optional instance to populate.
     * @return {module:model/LnrpcHopHint} The populated <code>LnrpcHopHint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcHopHint();

            if (data.hasOwnProperty('node_id')) {
                obj['node_id'] = ApiClient.convertToType(data['node_id'], 'String');
            }
            if (data.hasOwnProperty('chan_id')) {
                obj['chan_id'] = ApiClient.convertToType(data['chan_id'], 'String');
            }
            if (data.hasOwnProperty('fee_base_msat')) {
                obj['fee_base_msat'] = ApiClient.convertToType(data['fee_base_msat'], 'Number');
            }
            if (data.hasOwnProperty('fee_proportional_millionths')) {
                obj['fee_proportional_millionths'] = ApiClient.convertToType(data['fee_proportional_millionths'], 'Number');
            }
            if (data.hasOwnProperty('cltv_expiry_delta')) {
                obj['cltv_expiry_delta'] = ApiClient.convertToType(data['cltv_expiry_delta'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The public key of the node at the start of the channel.
 * @member {String} node_id
 */
LnrpcHopHint.prototype['node_id'] = undefined;

/**
 * The unique identifier of the channel.
 * @member {String} chan_id
 */
LnrpcHopHint.prototype['chan_id'] = undefined;

/**
 * The base fee of the channel denominated in millisatoshis.
 * @member {Number} fee_base_msat
 */
LnrpcHopHint.prototype['fee_base_msat'] = undefined;

/**
 * The fee rate of the channel for sending one satoshi across it denominated in millionths of a satoshi.
 * @member {Number} fee_proportional_millionths
 */
LnrpcHopHint.prototype['fee_proportional_millionths'] = undefined;

/**
 * The time-lock delta of the channel.
 * @member {Number} cltv_expiry_delta
 */
LnrpcHopHint.prototype['cltv_expiry_delta'] = undefined;






export default LnrpcHopHint;

