/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcChannelBackup from './LnrpcChannelBackup';

/**
 * The LnrpcChannelBackups model module.
 * @module model/LnrpcChannelBackups
 * @version version not set
 */
class LnrpcChannelBackups {
    /**
     * Constructs a new <code>LnrpcChannelBackups</code>.
     * @alias module:model/LnrpcChannelBackups
     */
    constructor() { 
        LnrpcChannelBackups.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcChannelBackups</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcChannelBackups} obj Optional instance to populate.
     * @return {module:model/LnrpcChannelBackups} The populated <code>LnrpcChannelBackups</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcChannelBackups();

            if (data.hasOwnProperty('chan_backups')) {
                obj['chan_backups'] = ApiClient.convertToType(data['chan_backups'], [LnrpcChannelBackup]);
            }
        }
        return obj;
    }


}

/**
 * A set of single-chan static channel backups.
 * @member {Array.<module:model/LnrpcChannelBackup>} chan_backups
 */
LnrpcChannelBackups.prototype['chan_backups'] = undefined;






export default LnrpcChannelBackups;

