/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcMacaroonPermission from './LnrpcMacaroonPermission';

/**
 * The LnrpcBakeMacaroonRequest model module.
 * @module model/LnrpcBakeMacaroonRequest
 * @version version not set
 */
class LnrpcBakeMacaroonRequest {
    /**
     * Constructs a new <code>LnrpcBakeMacaroonRequest</code>.
     * @alias module:model/LnrpcBakeMacaroonRequest
     */
    constructor() { 
        LnrpcBakeMacaroonRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LnrpcBakeMacaroonRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LnrpcBakeMacaroonRequest} obj Optional instance to populate.
     * @return {module:model/LnrpcBakeMacaroonRequest} The populated <code>LnrpcBakeMacaroonRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LnrpcBakeMacaroonRequest();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [LnrpcMacaroonPermission]);
            }
            if (data.hasOwnProperty('root_key_id')) {
                obj['root_key_id'] = ApiClient.convertToType(data['root_key_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The list of permissions the new macaroon should grant.
 * @member {Array.<module:model/LnrpcMacaroonPermission>} permissions
 */
LnrpcBakeMacaroonRequest.prototype['permissions'] = undefined;

/**
 * The root key ID used to create the macaroon, must be a positive integer.
 * @member {String} root_key_id
 */
LnrpcBakeMacaroonRequest.prototype['root_key_id'] = undefined;






export default LnrpcBakeMacaroonRequest;

