/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentPaymentStatus.
* @enum {}
* @readonly
*/
export default class PaymentPaymentStatus {
    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN" = "UNKNOWN";

    
        /**
         * value: "IN_FLIGHT"
         * @const
         */
        "IN_FLIGHT" = "IN_FLIGHT";

    
        /**
         * value: "SUCCEEDED"
         * @const
         */
        "SUCCEEDED" = "SUCCEEDED";

    
        /**
         * value: "FAILED"
         * @const
         */
        "FAILED" = "FAILED";

    

    /**
    * Returns a <code>PaymentPaymentStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentPaymentStatus} The enum <code>PaymentPaymentStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

