/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PeerSyncType.
* @enum {}
* @readonly
*/
export default class PeerSyncType {
    
        /**
         * value: "UNKNOWN_SYNC"
         * @const
         */
        "UNKNOWN_SYNC" = "UNKNOWN_SYNC";

    
        /**
         * value: "ACTIVE_SYNC"
         * @const
         */
        "ACTIVE_SYNC" = "ACTIVE_SYNC";

    
        /**
         * value: "PASSIVE_SYNC"
         * @const
         */
        "PASSIVE_SYNC" = "PASSIVE_SYNC";

    
        /**
         * value: "PINNED_SYNC"
         * @const
         */
        "PINNED_SYNC" = "PINNED_SYNC";

    

    /**
    * Returns a <code>PeerSyncType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PeerSyncType} The enum <code>PeerSyncType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

