/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProtobufAny from './ProtobufAny';

/**
 * The RuntimeStreamError model module.
 * @module model/RuntimeStreamError
 * @version version not set
 */
class RuntimeStreamError {
    /**
     * Constructs a new <code>RuntimeStreamError</code>.
     * @alias module:model/RuntimeStreamError
     */
    constructor() { 
        RuntimeStreamError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuntimeStreamError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuntimeStreamError} obj Optional instance to populate.
     * @return {module:model/RuntimeStreamError} The populated <code>RuntimeStreamError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuntimeStreamError();

            if (data.hasOwnProperty('grpc_code')) {
                obj['grpc_code'] = ApiClient.convertToType(data['grpc_code'], 'Number');
            }
            if (data.hasOwnProperty('http_code')) {
                obj['http_code'] = ApiClient.convertToType(data['http_code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('http_status')) {
                obj['http_status'] = ApiClient.convertToType(data['http_status'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], [ProtobufAny]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} grpc_code
 */
RuntimeStreamError.prototype['grpc_code'] = undefined;

/**
 * @member {Number} http_code
 */
RuntimeStreamError.prototype['http_code'] = undefined;

/**
 * @member {String} message
 */
RuntimeStreamError.prototype['message'] = undefined;

/**
 * @member {String} http_status
 */
RuntimeStreamError.prototype['http_status'] = undefined;

/**
 * @member {Array.<module:model/ProtobufAny>} details
 */
RuntimeStreamError.prototype['details'] = undefined;






export default RuntimeStreamError;

