/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LnrpcSendResponse from './LnrpcSendResponse';
import RuntimeStreamError from './RuntimeStreamError';

/**
 * The StreamResultOfLnrpcSendResponse model module.
 * @module model/StreamResultOfLnrpcSendResponse
 * @version version not set
 */
class StreamResultOfLnrpcSendResponse {
    /**
     * Constructs a new <code>StreamResultOfLnrpcSendResponse</code>.
     * @alias module:model/StreamResultOfLnrpcSendResponse
     */
    constructor() { 
        StreamResultOfLnrpcSendResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StreamResultOfLnrpcSendResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StreamResultOfLnrpcSendResponse} obj Optional instance to populate.
     * @return {module:model/StreamResultOfLnrpcSendResponse} The populated <code>StreamResultOfLnrpcSendResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StreamResultOfLnrpcSendResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = LnrpcSendResponse.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = RuntimeStreamError.constructFromObject(data['error']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LnrpcSendResponse} result
 */
StreamResultOfLnrpcSendResponse.prototype['result'] = undefined;

/**
 * @member {module:model/RuntimeStreamError} error
 */
StreamResultOfLnrpcSendResponse.prototype['error'] = undefined;






export default StreamResultOfLnrpcSendResponse;

