/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ForceClosedChannelAnchorState {
    Limbo = 'LIMBO',
    Recovered = 'RECOVERED',
    Lost = 'LOST'
}

export function ForceClosedChannelAnchorStateFromJSON(json: any): ForceClosedChannelAnchorState {
    return ForceClosedChannelAnchorStateFromJSONTyped(json, false);
}

export function ForceClosedChannelAnchorStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceClosedChannelAnchorState {
    return json as ForceClosedChannelAnchorState;
}

export function ForceClosedChannelAnchorStateToJSON(value?: ForceClosedChannelAnchorState | null): any {
    return value as any;
}

