/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum HTLCAttemptHTLCStatus {
    InFlight = 'IN_FLIGHT',
    Succeeded = 'SUCCEEDED',
    Failed = 'FAILED'
}

export function HTLCAttemptHTLCStatusFromJSON(json: any): HTLCAttemptHTLCStatus {
    return HTLCAttemptHTLCStatusFromJSONTyped(json, false);
}

export function HTLCAttemptHTLCStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTLCAttemptHTLCStatus {
    return json as HTLCAttemptHTLCStatus;
}

export function HTLCAttemptHTLCStatusToJSON(value?: HTLCAttemptHTLCStatus | null): any {
    return value as any;
}

