/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcFundingPsbtFinalize
 */
export interface LnrpcFundingPsbtFinalize {
    /**
     * The funded PSBT that contains all witness data to send the exact channel
     * capacity amount to the PK script returned in the open channel message in a
     * previous step. Cannot be set at the same time as final_raw_tx.
     * @type {string}
     * @memberof LnrpcFundingPsbtFinalize
     */
    signedPsbt?: string;
    /**
     * The pending channel ID of the channel to get the PSBT for.
     * @type {string}
     * @memberof LnrpcFundingPsbtFinalize
     */
    pendingChanId?: string;
    /**
     * As an alternative to the signed PSBT with all witness data, the final raw
     * wire format transaction can also be specified directly. Cannot be set at the
     * same time as signed_psbt.
     * @type {string}
     * @memberof LnrpcFundingPsbtFinalize
     */
    finalRawTx?: string;
}

export function LnrpcFundingPsbtFinalizeFromJSON(json: any): LnrpcFundingPsbtFinalize {
    return LnrpcFundingPsbtFinalizeFromJSONTyped(json, false);
}

export function LnrpcFundingPsbtFinalizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcFundingPsbtFinalize {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'signedPsbt': !exists(json, 'signed_psbt') ? undefined : json['signed_psbt'],
        'pendingChanId': !exists(json, 'pending_chan_id') ? undefined : json['pending_chan_id'],
        'finalRawTx': !exists(json, 'final_raw_tx') ? undefined : json['final_raw_tx'],
    };
}

export function LnrpcFundingPsbtFinalizeToJSON(value?: LnrpcFundingPsbtFinalize | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'signed_psbt': value.signedPsbt,
        'pending_chan_id': value.pendingChanId,
        'final_raw_tx': value.finalRawTx,
    };
}

