/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcInvoice,
    LnrpcInvoiceFromJSON,
    LnrpcInvoiceFromJSONTyped,
    LnrpcInvoiceToJSON,
} from './';

/**
 * 
 * @export
 * @interface LnrpcListInvoiceResponse
 */
export interface LnrpcListInvoiceResponse {
    /**
     * A list of invoices from the time slice of the time series specified in the
     * request.
     * @type {Array<LnrpcInvoice>}
     * @memberof LnrpcListInvoiceResponse
     */
    invoices?: Array<LnrpcInvoice>;
    /**
     * The index of the last item in the set of returned invoices. This can be used
     * to seek further, pagination style.
     * @type {string}
     * @memberof LnrpcListInvoiceResponse
     */
    lastIndexOffset?: string;
    /**
     * The index of the last item in the set of returned invoices. This can be used
     * to seek backwards, pagination style.
     * @type {string}
     * @memberof LnrpcListInvoiceResponse
     */
    firstIndexOffset?: string;
}

export function LnrpcListInvoiceResponseFromJSON(json: any): LnrpcListInvoiceResponse {
    return LnrpcListInvoiceResponseFromJSONTyped(json, false);
}

export function LnrpcListInvoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcListInvoiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invoices': !exists(json, 'invoices') ? undefined : ((json['invoices'] as Array<any>).map(LnrpcInvoiceFromJSON)),
        'lastIndexOffset': !exists(json, 'last_index_offset') ? undefined : json['last_index_offset'],
        'firstIndexOffset': !exists(json, 'first_index_offset') ? undefined : json['first_index_offset'],
    };
}

export function LnrpcListInvoiceResponseToJSON(value?: LnrpcListInvoiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invoices': value.invoices === undefined ? undefined : ((value.invoices as Array<any>).map(LnrpcInvoiceToJSON)),
        'last_index_offset': value.lastIndexOffset,
        'first_index_offset': value.firstIndexOffset,
    };
}

