/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcChannelEdge,
    LnrpcChannelEdgeFromJSON,
    LnrpcChannelEdgeFromJSONTyped,
    LnrpcChannelEdgeToJSON,
    LnrpcLightningNode,
    LnrpcLightningNodeFromJSON,
    LnrpcLightningNodeFromJSONTyped,
    LnrpcLightningNodeToJSON,
} from './';

/**
 * Returns a new instance of the directed channel graph.
 * @export
 * @interface LnrpcChannelGraph
 */
export interface LnrpcChannelGraph {
    /**
     * 
     * @type {Array<LnrpcLightningNode>}
     * @memberof LnrpcChannelGraph
     */
    nodes?: Array<LnrpcLightningNode>;
    /**
     * 
     * @type {Array<LnrpcChannelEdge>}
     * @memberof LnrpcChannelGraph
     */
    edges?: Array<LnrpcChannelEdge>;
}

export function LnrpcChannelGraphFromJSON(json: any): LnrpcChannelGraph {
    return LnrpcChannelGraphFromJSONTyped(json, false);
}

export function LnrpcChannelGraphFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcChannelGraph {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nodes': !exists(json, 'nodes') ? undefined : ((json['nodes'] as Array<any>).map(LnrpcLightningNodeFromJSON)),
        'edges': !exists(json, 'edges') ? undefined : ((json['edges'] as Array<any>).map(LnrpcChannelEdgeFromJSON)),
    };
}

export function LnrpcChannelGraphToJSON(value?: LnrpcChannelGraph | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nodes': value.nodes === undefined ? undefined : ((value.nodes as Array<any>).map(LnrpcLightningNodeToJSON)),
        'edges': value.edges === undefined ? undefined : ((value.edges as Array<any>).map(LnrpcChannelEdgeToJSON)),
    };
}

