/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcTimestampedError
 */
export interface LnrpcTimestampedError {
    /**
     * The unix timestamp in seconds when the error occurred.
     * @type {string}
     * @memberof LnrpcTimestampedError
     */
    timestamp?: string;
    /**
     * The string representation of the error sent by our peer.
     * @type {string}
     * @memberof LnrpcTimestampedError
     */
    error?: string;
}

export function LnrpcTimestampedErrorFromJSON(json: any): LnrpcTimestampedError {
    return LnrpcTimestampedErrorFromJSONTyped(json, false);
}

export function LnrpcTimestampedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcTimestampedError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function LnrpcTimestampedErrorToJSON(value?: LnrpcTimestampedError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'error': value.error,
    };
}

