/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcListMacaroonIDsResponse
 */
export interface LnrpcListMacaroonIDsResponse {
    /**
     * The list of root key IDs that are in use.
     * @type {Array<string>}
     * @memberof LnrpcListMacaroonIDsResponse
     */
    rootKeyIds?: Array<string>;
}

export function LnrpcListMacaroonIDsResponseFromJSON(json: any): LnrpcListMacaroonIDsResponse {
    return LnrpcListMacaroonIDsResponseFromJSONTyped(json, false);
}

export function LnrpcListMacaroonIDsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcListMacaroonIDsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rootKeyIds': !exists(json, 'root_key_ids') ? undefined : json['root_key_ids'],
    };
}

export function LnrpcListMacaroonIDsResponseToJSON(value?: LnrpcListMacaroonIDsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'root_key_ids': value.rootKeyIds,
    };
}

