/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcKeyLocator,
    LnrpcKeyLocatorFromJSON,
    LnrpcKeyLocatorFromJSONTyped,
    LnrpcKeyLocatorToJSON,
} from './';

/**
 * 
 * @export
 * @interface LnrpcKeyDescriptor
 */
export interface LnrpcKeyDescriptor {
    /**
     * The raw bytes of the key being identified.
     * @type {string}
     * @memberof LnrpcKeyDescriptor
     */
    rawKeyBytes?: string;
    /**
     * 
     * @type {LnrpcKeyLocator}
     * @memberof LnrpcKeyDescriptor
     */
    keyLoc?: LnrpcKeyLocator;
}

export function LnrpcKeyDescriptorFromJSON(json: any): LnrpcKeyDescriptor {
    return LnrpcKeyDescriptorFromJSONTyped(json, false);
}

export function LnrpcKeyDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcKeyDescriptor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rawKeyBytes': !exists(json, 'raw_key_bytes') ? undefined : json['raw_key_bytes'],
        'keyLoc': !exists(json, 'key_loc') ? undefined : LnrpcKeyLocatorFromJSON(json['key_loc']),
    };
}

export function LnrpcKeyDescriptorToJSON(value?: LnrpcKeyDescriptor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'raw_key_bytes': value.rawKeyBytes,
        'key_loc': LnrpcKeyLocatorToJSON(value.keyLoc),
    };
}

