/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcChannelPoint,
    LnrpcChannelPointFromJSON,
    LnrpcChannelPointFromJSONTyped,
    LnrpcChannelPointToJSON,
} from './';

/**
 * 
 * @export
 * @interface LnrpcChannelOpenUpdate
 */
export interface LnrpcChannelOpenUpdate {
    /**
     * 
     * @type {LnrpcChannelPoint}
     * @memberof LnrpcChannelOpenUpdate
     */
    channelPoint?: LnrpcChannelPoint;
}

export function LnrpcChannelOpenUpdateFromJSON(json: any): LnrpcChannelOpenUpdate {
    return LnrpcChannelOpenUpdateFromJSONTyped(json, false);
}

export function LnrpcChannelOpenUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcChannelOpenUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelPoint': !exists(json, 'channel_point') ? undefined : LnrpcChannelPointFromJSON(json['channel_point']),
    };
}

export function LnrpcChannelOpenUpdateToJSON(value?: LnrpcChannelOpenUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_point': LnrpcChannelPointToJSON(value.channelPoint),
    };
}

