/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcForwardingEvent,
    LnrpcForwardingEventFromJSON,
    LnrpcForwardingEventFromJSONTyped,
    LnrpcForwardingEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface LnrpcForwardingHistoryResponse
 */
export interface LnrpcForwardingHistoryResponse {
    /**
     * A list of forwarding events from the time slice of the time series
     * specified in the request.
     * @type {Array<LnrpcForwardingEvent>}
     * @memberof LnrpcForwardingHistoryResponse
     */
    forwardingEvents?: Array<LnrpcForwardingEvent>;
    /**
     * The index of the last time in the set of returned forwarding events. Can
     * be used to seek further, pagination style.
     * @type {number}
     * @memberof LnrpcForwardingHistoryResponse
     */
    lastOffsetIndex?: number;
}

export function LnrpcForwardingHistoryResponseFromJSON(json: any): LnrpcForwardingHistoryResponse {
    return LnrpcForwardingHistoryResponseFromJSONTyped(json, false);
}

export function LnrpcForwardingHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcForwardingHistoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forwardingEvents': !exists(json, 'forwarding_events') ? undefined : ((json['forwarding_events'] as Array<any>).map(LnrpcForwardingEventFromJSON)),
        'lastOffsetIndex': !exists(json, 'last_offset_index') ? undefined : json['last_offset_index'],
    };
}

export function LnrpcForwardingHistoryResponseToJSON(value?: LnrpcForwardingHistoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forwarding_events': value.forwardingEvents === undefined ? undefined : ((value.forwardingEvents as Array<any>).map(LnrpcForwardingEventToJSON)),
        'last_offset_index': value.lastOffsetIndex,
    };
}

