/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcFundingShimCancel
 */
export interface LnrpcFundingShimCancel {
    /**
     * The pending channel ID of the channel to cancel the funding shim for.
     * @type {string}
     * @memberof LnrpcFundingShimCancel
     */
    pendingChanId?: string;
}

export function LnrpcFundingShimCancelFromJSON(json: any): LnrpcFundingShimCancel {
    return LnrpcFundingShimCancelFromJSONTyped(json, false);
}

export function LnrpcFundingShimCancelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcFundingShimCancel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pendingChanId': !exists(json, 'pending_chan_id') ? undefined : json['pending_chan_id'],
    };
}

export function LnrpcFundingShimCancelToJSON(value?: LnrpcFundingShimCancel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pending_chan_id': value.pendingChanId,
    };
}

