/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcFundingPsbtVerify
 */
export interface LnrpcFundingPsbtVerify {
    /**
     * The funded but not yet signed PSBT that sends the exact channel capacity
     * amount to the PK script returned in the open channel message in a previous
     * step.
     * @type {string}
     * @memberof LnrpcFundingPsbtVerify
     */
    fundedPsbt?: string;
    /**
     * The pending channel ID of the channel to get the PSBT for.
     * @type {string}
     * @memberof LnrpcFundingPsbtVerify
     */
    pendingChanId?: string;
}

export function LnrpcFundingPsbtVerifyFromJSON(json: any): LnrpcFundingPsbtVerify {
    return LnrpcFundingPsbtVerifyFromJSONTyped(json, false);
}

export function LnrpcFundingPsbtVerifyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcFundingPsbtVerify {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fundedPsbt': !exists(json, 'funded_psbt') ? undefined : json['funded_psbt'],
        'pendingChanId': !exists(json, 'pending_chan_id') ? undefined : json['pending_chan_id'],
    };
}

export function LnrpcFundingPsbtVerifyToJSON(value?: LnrpcFundingPsbtVerify | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'funded_psbt': value.fundedPsbt,
        'pending_chan_id': value.pendingChanId,
    };
}

