/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcAMPRecord
 */
export interface LnrpcAMPRecord {
    /**
     * 
     * @type {string}
     * @memberof LnrpcAMPRecord
     */
    rootShare?: string;
    /**
     * 
     * @type {string}
     * @memberof LnrpcAMPRecord
     */
    setId?: string;
    /**
     * 
     * @type {number}
     * @memberof LnrpcAMPRecord
     */
    childIndex?: number;
}

export function LnrpcAMPRecordFromJSON(json: any): LnrpcAMPRecord {
    return LnrpcAMPRecordFromJSONTyped(json, false);
}

export function LnrpcAMPRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcAMPRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rootShare': !exists(json, 'root_share') ? undefined : json['root_share'],
        'setId': !exists(json, 'set_id') ? undefined : json['set_id'],
        'childIndex': !exists(json, 'child_index') ? undefined : json['child_index'],
    };
}

export function LnrpcAMPRecordToJSON(value?: LnrpcAMPRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'root_share': value.rootShare,
        'set_id': value.setId,
        'child_index': value.childIndex,
    };
}

