/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcVerifyMessageRequest
 */
export interface LnrpcVerifyMessageRequest {
    /**
     * The message over which the signature is to be verified. When using REST,
     * this field must be encoded as base64.
     * @type {string}
     * @memberof LnrpcVerifyMessageRequest
     */
    msg?: string;
    /**
     * 
     * @type {string}
     * @memberof LnrpcVerifyMessageRequest
     */
    signature?: string;
}

export function LnrpcVerifyMessageRequestFromJSON(json: any): LnrpcVerifyMessageRequest {
    return LnrpcVerifyMessageRequestFromJSONTyped(json, false);
}

export function LnrpcVerifyMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcVerifyMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'signature': !exists(json, 'signature') ? undefined : json['signature'],
    };
}

export function LnrpcVerifyMessageRequestToJSON(value?: LnrpcVerifyMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
        'signature': value.signature,
    };
}

