/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcLightningAddress
 */
export interface LnrpcLightningAddress {
    /**
     * 
     * @type {string}
     * @memberof LnrpcLightningAddress
     */
    pubkey?: string;
    /**
     * 
     * @type {string}
     * @memberof LnrpcLightningAddress
     */
    host?: string;
}

export function LnrpcLightningAddressFromJSON(json: any): LnrpcLightningAddress {
    return LnrpcLightningAddressFromJSONTyped(json, false);
}

export function LnrpcLightningAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcLightningAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pubkey': !exists(json, 'pubkey') ? undefined : json['pubkey'],
        'host': !exists(json, 'host') ? undefined : json['host'],
    };
}

export function LnrpcLightningAddressToJSON(value?: LnrpcLightningAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pubkey': value.pubkey,
        'host': value.host,
    };
}

