/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcWalletAccountBalance
 */
export interface LnrpcWalletAccountBalance {
    /**
     * The confirmed balance of the account (with >= 1 confirmations).
     * @type {string}
     * @memberof LnrpcWalletAccountBalance
     */
    confirmedBalance?: string;
    /**
     * The unconfirmed balance of the account (with 0 confirmations).
     * @type {string}
     * @memberof LnrpcWalletAccountBalance
     */
    unconfirmedBalance?: string;
}

export function LnrpcWalletAccountBalanceFromJSON(json: any): LnrpcWalletAccountBalance {
    return LnrpcWalletAccountBalanceFromJSONTyped(json, false);
}

export function LnrpcWalletAccountBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcWalletAccountBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'confirmedBalance': !exists(json, 'confirmed_balance') ? undefined : json['confirmed_balance'],
        'unconfirmedBalance': !exists(json, 'unconfirmed_balance') ? undefined : json['unconfirmed_balance'],
    };
}

export function LnrpcWalletAccountBalanceToJSON(value?: LnrpcWalletAccountBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'confirmed_balance': value.confirmedBalance,
        'unconfirmed_balance': value.unconfirmedBalance,
    };
}

