/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LnrpcAddInvoiceResponse
 */
export interface LnrpcAddInvoiceResponse {
    /**
     * 
     * @type {string}
     * @memberof LnrpcAddInvoiceResponse
     */
    rHash?: string;
    /**
     * A bare-bones invoice for a payment within the Lightning Network. With the
     * details of the invoice, the sender has all the data necessary to send a
     * payment to the recipient.
     * @type {string}
     * @memberof LnrpcAddInvoiceResponse
     */
    paymentRequest?: string;
    /**
     * The "add" index of this invoice. Each newly created invoice will increment
     * this index making it monotonically increasing. Callers to the
     * SubscribeInvoices call can use this to instantly get notified of all added
     * invoices with an add_index greater than this one.
     * @type {string}
     * @memberof LnrpcAddInvoiceResponse
     */
    addIndex?: string;
    /**
     * The payment address of the generated invoice. This value should be used
     * in all payments for this invoice as we require it for end to end
     * security.
     * @type {string}
     * @memberof LnrpcAddInvoiceResponse
     */
    paymentAddr?: string;
}

export function LnrpcAddInvoiceResponseFromJSON(json: any): LnrpcAddInvoiceResponse {
    return LnrpcAddInvoiceResponseFromJSONTyped(json, false);
}

export function LnrpcAddInvoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcAddInvoiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rHash': !exists(json, 'r_hash') ? undefined : json['r_hash'],
        'paymentRequest': !exists(json, 'payment_request') ? undefined : json['payment_request'],
        'addIndex': !exists(json, 'add_index') ? undefined : json['add_index'],
        'paymentAddr': !exists(json, 'payment_addr') ? undefined : json['payment_addr'],
    };
}

export function LnrpcAddInvoiceResponseToJSON(value?: LnrpcAddInvoiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'r_hash': value.rHash,
        'payment_request': value.paymentRequest,
        'add_index': value.addIndex,
        'payment_addr': value.paymentAddr,
    };
}

