/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcAddressType,
    LnrpcAddressTypeFromJSON,
    LnrpcAddressTypeFromJSONTyped,
    LnrpcAddressTypeToJSON,
    LnrpcOutPoint,
    LnrpcOutPointFromJSON,
    LnrpcOutPointFromJSONTyped,
    LnrpcOutPointToJSON,
} from './';

/**
 * 
 * @export
 * @interface LnrpcUtxo
 */
export interface LnrpcUtxo {
    /**
     * 
     * @type {LnrpcAddressType}
     * @memberof LnrpcUtxo
     */
    addressType?: LnrpcAddressType;
    /**
     * 
     * @type {string}
     * @memberof LnrpcUtxo
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof LnrpcUtxo
     */
    amountSat?: string;
    /**
     * 
     * @type {string}
     * @memberof LnrpcUtxo
     */
    pkScript?: string;
    /**
     * 
     * @type {LnrpcOutPoint}
     * @memberof LnrpcUtxo
     */
    outpoint?: LnrpcOutPoint;
    /**
     * 
     * @type {string}
     * @memberof LnrpcUtxo
     */
    confirmations?: string;
}

export function LnrpcUtxoFromJSON(json: any): LnrpcUtxo {
    return LnrpcUtxoFromJSONTyped(json, false);
}

export function LnrpcUtxoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LnrpcUtxo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressType': !exists(json, 'address_type') ? undefined : LnrpcAddressTypeFromJSON(json['address_type']),
        'address': !exists(json, 'address') ? undefined : json['address'],
        'amountSat': !exists(json, 'amount_sat') ? undefined : json['amount_sat'],
        'pkScript': !exists(json, 'pk_script') ? undefined : json['pk_script'],
        'outpoint': !exists(json, 'outpoint') ? undefined : LnrpcOutPointFromJSON(json['outpoint']),
        'confirmations': !exists(json, 'confirmations') ? undefined : json['confirmations'],
    };
}

export function LnrpcUtxoToJSON(value?: LnrpcUtxo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address_type': LnrpcAddressTypeToJSON(value.addressType),
        'address': value.address,
        'amount_sat': value.amountSat,
        'pk_script': value.pkScript,
        'outpoint': LnrpcOutPointToJSON(value.outpoint),
        'confirmations': value.confirmations,
    };
}

