/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PendingChannelsResponsePendingChannel,
    PendingChannelsResponsePendingChannelFromJSON,
    PendingChannelsResponsePendingChannelFromJSONTyped,
    PendingChannelsResponsePendingChannelToJSON,
} from './';

/**
 * 
 * @export
 * @interface PendingChannelsResponseClosedChannel
 */
export interface PendingChannelsResponseClosedChannel {
    /**
     * 
     * @type {PendingChannelsResponsePendingChannel}
     * @memberof PendingChannelsResponseClosedChannel
     */
    channel?: PendingChannelsResponsePendingChannel;
    /**
     * 
     * @type {string}
     * @memberof PendingChannelsResponseClosedChannel
     */
    closingTxid?: string;
}

export function PendingChannelsResponseClosedChannelFromJSON(json: any): PendingChannelsResponseClosedChannel {
    return PendingChannelsResponseClosedChannelFromJSONTyped(json, false);
}

export function PendingChannelsResponseClosedChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingChannelsResponseClosedChannel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channel': !exists(json, 'channel') ? undefined : PendingChannelsResponsePendingChannelFromJSON(json['channel']),
        'closingTxid': !exists(json, 'closing_txid') ? undefined : json['closing_txid'],
    };
}

export function PendingChannelsResponseClosedChannelToJSON(value?: PendingChannelsResponseClosedChannel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel': PendingChannelsResponsePendingChannelToJSON(value.channel),
        'closing_txid': value.closingTxid,
    };
}

