/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcChanBackupSnapshot,
    LnrpcChanBackupSnapshotFromJSON,
    LnrpcChanBackupSnapshotFromJSONTyped,
    LnrpcChanBackupSnapshotToJSON,
    RuntimeStreamError,
    RuntimeStreamErrorFromJSON,
    RuntimeStreamErrorFromJSONTyped,
    RuntimeStreamErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface StreamResultOfLnrpcChanBackupSnapshot
 */
export interface StreamResultOfLnrpcChanBackupSnapshot {
    /**
     * 
     * @type {LnrpcChanBackupSnapshot}
     * @memberof StreamResultOfLnrpcChanBackupSnapshot
     */
    result?: LnrpcChanBackupSnapshot;
    /**
     * 
     * @type {RuntimeStreamError}
     * @memberof StreamResultOfLnrpcChanBackupSnapshot
     */
    error?: RuntimeStreamError;
}

export function StreamResultOfLnrpcChanBackupSnapshotFromJSON(json: any): StreamResultOfLnrpcChanBackupSnapshot {
    return StreamResultOfLnrpcChanBackupSnapshotFromJSONTyped(json, false);
}

export function StreamResultOfLnrpcChanBackupSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamResultOfLnrpcChanBackupSnapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : LnrpcChanBackupSnapshotFromJSON(json['result']),
        'error': !exists(json, 'error') ? undefined : RuntimeStreamErrorFromJSON(json['error']),
    };
}

export function StreamResultOfLnrpcChanBackupSnapshotToJSON(value?: StreamResultOfLnrpcChanBackupSnapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': LnrpcChanBackupSnapshotToJSON(value.result),
        'error': RuntimeStreamErrorToJSON(value.error),
    };
}

