/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcSendResponse,
    LnrpcSendResponseFromJSON,
    LnrpcSendResponseFromJSONTyped,
    LnrpcSendResponseToJSON,
    RuntimeStreamError,
    RuntimeStreamErrorFromJSON,
    RuntimeStreamErrorFromJSONTyped,
    RuntimeStreamErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface StreamResultOfLnrpcSendResponse
 */
export interface StreamResultOfLnrpcSendResponse {
    /**
     * 
     * @type {LnrpcSendResponse}
     * @memberof StreamResultOfLnrpcSendResponse
     */
    result?: LnrpcSendResponse;
    /**
     * 
     * @type {RuntimeStreamError}
     * @memberof StreamResultOfLnrpcSendResponse
     */
    error?: RuntimeStreamError;
}

export function StreamResultOfLnrpcSendResponseFromJSON(json: any): StreamResultOfLnrpcSendResponse {
    return StreamResultOfLnrpcSendResponseFromJSONTyped(json, false);
}

export function StreamResultOfLnrpcSendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamResultOfLnrpcSendResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : LnrpcSendResponseFromJSON(json['result']),
        'error': !exists(json, 'error') ? undefined : RuntimeStreamErrorFromJSON(json['error']),
    };
}

export function StreamResultOfLnrpcSendResponseToJSON(value?: StreamResultOfLnrpcSendResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': LnrpcSendResponseToJSON(value.result),
        'error': RuntimeStreamErrorToJSON(value.error),
    };
}

