/* tslint:disable */
/* eslint-disable */
/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LnrpcInvoice,
    LnrpcInvoiceFromJSON,
    LnrpcInvoiceFromJSONTyped,
    LnrpcInvoiceToJSON,
    RuntimeStreamError,
    RuntimeStreamErrorFromJSON,
    RuntimeStreamErrorFromJSONTyped,
    RuntimeStreamErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface StreamResultOfLnrpcInvoice
 */
export interface StreamResultOfLnrpcInvoice {
    /**
     * 
     * @type {LnrpcInvoice}
     * @memberof StreamResultOfLnrpcInvoice
     */
    result?: LnrpcInvoice;
    /**
     * 
     * @type {RuntimeStreamError}
     * @memberof StreamResultOfLnrpcInvoice
     */
    error?: RuntimeStreamError;
}

export function StreamResultOfLnrpcInvoiceFromJSON(json: any): StreamResultOfLnrpcInvoice {
    return StreamResultOfLnrpcInvoiceFromJSONTyped(json, false);
}

export function StreamResultOfLnrpcInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamResultOfLnrpcInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : LnrpcInvoiceFromJSON(json['result']),
        'error': !exists(json, 'error') ? undefined : RuntimeStreamErrorFromJSON(json['error']),
    };
}

export function StreamResultOfLnrpcInvoiceToJSON(value?: StreamResultOfLnrpcInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': LnrpcInvoiceToJSON(value.result),
        'error': RuntimeStreamErrorToJSON(value.error),
    };
}

