/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcNodeUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcNodeUpdate', function() {
    it('should create an instance of LnrpcNodeUpdate', function() {
      // uncomment below and update the code to test LnrpcNodeUpdate
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be.a(lnd.LnrpcNodeUpdate);
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be();
    });

    it('should have the property identityKey (base name: "identity_key")', function() {
      // uncomment below and update the code to test the property identityKey
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be();
    });

    it('should have the property globalFeatures (base name: "global_features")', function() {
      // uncomment below and update the code to test the property globalFeatures
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be();
    });

    it('should have the property alias (base name: "alias")', function() {
      // uncomment below and update the code to test the property alias
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be();
    });

    it('should have the property nodeAddresses (base name: "node_addresses")', function() {
      // uncomment below and update the code to test the property nodeAddresses
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "features")', function() {
      // uncomment below and update the code to test the property features
      //var instance = new lnd.LnrpcNodeUpdate();
      //expect(instance).to.be();
    });

  });

}));
