/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcSendRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcSendRequest', function() {
    it('should create an instance of LnrpcSendRequest', function() {
      // uncomment below and update the code to test LnrpcSendRequest
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be.a(lnd.LnrpcSendRequest);
    });

    it('should have the property dest (base name: "dest")', function() {
      // uncomment below and update the code to test the property dest
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property destString (base name: "dest_string")', function() {
      // uncomment below and update the code to test the property destString
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property amt (base name: "amt")', function() {
      // uncomment below and update the code to test the property amt
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property amtMsat (base name: "amt_msat")', function() {
      // uncomment below and update the code to test the property amtMsat
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentHash (base name: "payment_hash")', function() {
      // uncomment below and update the code to test the property paymentHash
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentHashString (base name: "payment_hash_string")', function() {
      // uncomment below and update the code to test the property paymentHashString
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentRequest (base name: "payment_request")', function() {
      // uncomment below and update the code to test the property paymentRequest
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property finalCltvDelta (base name: "final_cltv_delta")', function() {
      // uncomment below and update the code to test the property finalCltvDelta
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property feeLimit (base name: "fee_limit")', function() {
      // uncomment below and update the code to test the property feeLimit
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property outgoingChanId (base name: "outgoing_chan_id")', function() {
      // uncomment below and update the code to test the property outgoingChanId
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastHopPubkey (base name: "last_hop_pubkey")', function() {
      // uncomment below and update the code to test the property lastHopPubkey
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property cltvLimit (base name: "cltv_limit")', function() {
      // uncomment below and update the code to test the property cltvLimit
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property destCustomRecords (base name: "dest_custom_records")', function() {
      // uncomment below and update the code to test the property destCustomRecords
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowSelfPayment (base name: "allow_self_payment")', function() {
      // uncomment below and update the code to test the property allowSelfPayment
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property destFeatures (base name: "dest_features")', function() {
      // uncomment below and update the code to test the property destFeatures
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentAddr (base name: "payment_addr")', function() {
      // uncomment below and update the code to test the property paymentAddr
      //var instance = new lnd.LnrpcSendRequest();
      //expect(instance).to.be();
    });

  });

}));
