/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcChannelCloseSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcChannelCloseSummary', function() {
    it('should create an instance of LnrpcChannelCloseSummary', function() {
      // uncomment below and update the code to test LnrpcChannelCloseSummary
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be.a(lnd.LnrpcChannelCloseSummary);
    });

    it('should have the property channelPoint (base name: "channel_point")', function() {
      // uncomment below and update the code to test the property channelPoint
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property chanId (base name: "chan_id")', function() {
      // uncomment below and update the code to test the property chanId
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property chainHash (base name: "chain_hash")', function() {
      // uncomment below and update the code to test the property chainHash
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property closingTxHash (base name: "closing_tx_hash")', function() {
      // uncomment below and update the code to test the property closingTxHash
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property remotePubkey (base name: "remote_pubkey")', function() {
      // uncomment below and update the code to test the property remotePubkey
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property capacity (base name: "capacity")', function() {
      // uncomment below and update the code to test the property capacity
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property closeHeight (base name: "close_height")', function() {
      // uncomment below and update the code to test the property closeHeight
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property settledBalance (base name: "settled_balance")', function() {
      // uncomment below and update the code to test the property settledBalance
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property timeLockedBalance (base name: "time_locked_balance")', function() {
      // uncomment below and update the code to test the property timeLockedBalance
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property closeType (base name: "close_type")', function() {
      // uncomment below and update the code to test the property closeType
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property openInitiator (base name: "open_initiator")', function() {
      // uncomment below and update the code to test the property openInitiator
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property closeInitiator (base name: "close_initiator")', function() {
      // uncomment below and update the code to test the property closeInitiator
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

    it('should have the property resolutions (base name: "resolutions")', function() {
      // uncomment below and update the code to test the property resolutions
      //var instance = new lnd.LnrpcChannelCloseSummary();
      //expect(instance).to.be();
    });

  });

}));
