/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcChannelAcceptRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcChannelAcceptRequest', function() {
    it('should create an instance of LnrpcChannelAcceptRequest', function() {
      // uncomment below and update the code to test LnrpcChannelAcceptRequest
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be.a(lnd.LnrpcChannelAcceptRequest);
    });

    it('should have the property nodePubkey (base name: "node_pubkey")', function() {
      // uncomment below and update the code to test the property nodePubkey
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property chainHash (base name: "chain_hash")', function() {
      // uncomment below and update the code to test the property chainHash
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property pendingChanId (base name: "pending_chan_id")', function() {
      // uncomment below and update the code to test the property pendingChanId
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property fundingAmt (base name: "funding_amt")', function() {
      // uncomment below and update the code to test the property fundingAmt
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property pushAmt (base name: "push_amt")', function() {
      // uncomment below and update the code to test the property pushAmt
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property dustLimit (base name: "dust_limit")', function() {
      // uncomment below and update the code to test the property dustLimit
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxValueInFlight (base name: "max_value_in_flight")', function() {
      // uncomment below and update the code to test the property maxValueInFlight
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property channelReserve (base name: "channel_reserve")', function() {
      // uncomment below and update the code to test the property channelReserve
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property minHtlc (base name: "min_htlc")', function() {
      // uncomment below and update the code to test the property minHtlc
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property feePerKw (base name: "fee_per_kw")', function() {
      // uncomment below and update the code to test the property feePerKw
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property csvDelay (base name: "csv_delay")', function() {
      // uncomment below and update the code to test the property csvDelay
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxAcceptedHtlcs (base name: "max_accepted_htlcs")', function() {
      // uncomment below and update the code to test the property maxAcceptedHtlcs
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

    it('should have the property channelFlags (base name: "channel_flags")', function() {
      // uncomment below and update the code to test the property channelFlags
      //var instance = new lnd.LnrpcChannelAcceptRequest();
      //expect(instance).to.be();
    });

  });

}));
