/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcNetworkInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcNetworkInfo', function() {
    it('should create an instance of LnrpcNetworkInfo', function() {
      // uncomment below and update the code to test LnrpcNetworkInfo
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be.a(lnd.LnrpcNetworkInfo);
    });

    it('should have the property graphDiameter (base name: "graph_diameter")', function() {
      // uncomment below and update the code to test the property graphDiameter
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property avgOutDegree (base name: "avg_out_degree")', function() {
      // uncomment below and update the code to test the property avgOutDegree
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property maxOutDegree (base name: "max_out_degree")', function() {
      // uncomment below and update the code to test the property maxOutDegree
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property numNodes (base name: "num_nodes")', function() {
      // uncomment below and update the code to test the property numNodes
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property numChannels (base name: "num_channels")', function() {
      // uncomment below and update the code to test the property numChannels
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property totalNetworkCapacity (base name: "total_network_capacity")', function() {
      // uncomment below and update the code to test the property totalNetworkCapacity
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property avgChannelSize (base name: "avg_channel_size")', function() {
      // uncomment below and update the code to test the property avgChannelSize
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property minChannelSize (base name: "min_channel_size")', function() {
      // uncomment below and update the code to test the property minChannelSize
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property maxChannelSize (base name: "max_channel_size")', function() {
      // uncomment below and update the code to test the property maxChannelSize
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property medianChannelSizeSat (base name: "median_channel_size_sat")', function() {
      // uncomment below and update the code to test the property medianChannelSizeSat
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

    it('should have the property numZombieChans (base name: "num_zombie_chans")', function() {
      // uncomment below and update the code to test the property numZombieChans
      //var instance = new lnd.LnrpcNetworkInfo();
      //expect(instance).to.be();
    });

  });

}));
