/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcPendingHTLC();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcPendingHTLC', function() {
    it('should create an instance of LnrpcPendingHTLC', function() {
      // uncomment below and update the code to test LnrpcPendingHTLC
      //var instance = new lnd.LnrpcPendingHTLC();
      //expect(instance).to.be.a(lnd.LnrpcPendingHTLC);
    });

    it('should have the property incoming (base name: "incoming")', function() {
      // uncomment below and update the code to test the property incoming
      //var instance = new lnd.LnrpcPendingHTLC();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new lnd.LnrpcPendingHTLC();
      //expect(instance).to.be();
    });

    it('should have the property outpoint (base name: "outpoint")', function() {
      // uncomment below and update the code to test the property outpoint
      //var instance = new lnd.LnrpcPendingHTLC();
      //expect(instance).to.be();
    });

    it('should have the property maturityHeight (base name: "maturity_height")', function() {
      // uncomment below and update the code to test the property maturityHeight
      //var instance = new lnd.LnrpcPendingHTLC();
      //expect(instance).to.be();
    });

    it('should have the property blocksTilMaturity (base name: "blocks_til_maturity")', function() {
      // uncomment below and update the code to test the property blocksTilMaturity
      //var instance = new lnd.LnrpcPendingHTLC();
      //expect(instance).to.be();
    });

    it('should have the property stage (base name: "stage")', function() {
      // uncomment below and update the code to test the property stage
      //var instance = new lnd.LnrpcPendingHTLC();
      //expect(instance).to.be();
    });

  });

}));
