/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcTransaction', function() {
    it('should create an instance of LnrpcTransaction', function() {
      // uncomment below and update the code to test LnrpcTransaction
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be.a(lnd.LnrpcTransaction);
    });

    it('should have the property txHash (base name: "tx_hash")', function() {
      // uncomment below and update the code to test the property txHash
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property numConfirmations (base name: "num_confirmations")', function() {
      // uncomment below and update the code to test the property numConfirmations
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property blockHash (base name: "block_hash")', function() {
      // uncomment below and update the code to test the property blockHash
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property blockHeight (base name: "block_height")', function() {
      // uncomment below and update the code to test the property blockHeight
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property timeStamp (base name: "time_stamp")', function() {
      // uncomment below and update the code to test the property timeStamp
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property totalFees (base name: "total_fees")', function() {
      // uncomment below and update the code to test the property totalFees
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property destAddresses (base name: "dest_addresses")', function() {
      // uncomment below and update the code to test the property destAddresses
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property rawTxHex (base name: "raw_tx_hex")', function() {
      // uncomment below and update the code to test the property rawTxHex
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instance = new lnd.LnrpcTransaction();
      //expect(instance).to.be();
    });

  });

}));
