/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcResolution();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcResolution', function() {
    it('should create an instance of LnrpcResolution', function() {
      // uncomment below and update the code to test LnrpcResolution
      //var instance = new lnd.LnrpcResolution();
      //expect(instance).to.be.a(lnd.LnrpcResolution);
    });

    it('should have the property resolutionType (base name: "resolution_type")', function() {
      // uncomment below and update the code to test the property resolutionType
      //var instance = new lnd.LnrpcResolution();
      //expect(instance).to.be();
    });

    it('should have the property outcome (base name: "outcome")', function() {
      // uncomment below and update the code to test the property outcome
      //var instance = new lnd.LnrpcResolution();
      //expect(instance).to.be();
    });

    it('should have the property outpoint (base name: "outpoint")', function() {
      // uncomment below and update the code to test the property outpoint
      //var instance = new lnd.LnrpcResolution();
      //expect(instance).to.be();
    });

    it('should have the property amountSat (base name: "amount_sat")', function() {
      // uncomment below and update the code to test the property amountSat
      //var instance = new lnd.LnrpcResolution();
      //expect(instance).to.be();
    });

    it('should have the property sweepTxid (base name: "sweep_txid")', function() {
      // uncomment below and update the code to test the property sweepTxid
      //var instance = new lnd.LnrpcResolution();
      //expect(instance).to.be();
    });

  });

}));
