/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcNodeInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcNodeInfo', function() {
    it('should create an instance of LnrpcNodeInfo', function() {
      // uncomment below and update the code to test LnrpcNodeInfo
      //var instance = new lnd.LnrpcNodeInfo();
      //expect(instance).to.be.a(lnd.LnrpcNodeInfo);
    });

    it('should have the property node (base name: "node")', function() {
      // uncomment below and update the code to test the property node
      //var instance = new lnd.LnrpcNodeInfo();
      //expect(instance).to.be();
    });

    it('should have the property numChannels (base name: "num_channels")', function() {
      // uncomment below and update the code to test the property numChannels
      //var instance = new lnd.LnrpcNodeInfo();
      //expect(instance).to.be();
    });

    it('should have the property totalCapacity (base name: "total_capacity")', function() {
      // uncomment below and update the code to test the property totalCapacity
      //var instance = new lnd.LnrpcNodeInfo();
      //expect(instance).to.be();
    });

    it('should have the property channels (base name: "channels")', function() {
      // uncomment below and update the code to test the property channels
      //var instance = new lnd.LnrpcNodeInfo();
      //expect(instance).to.be();
    });

  });

}));
