/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.lnd);
  }
}(this, function(expect, lnd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new lnd.LnrpcChannelAcceptResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LnrpcChannelAcceptResponse', function() {
    it('should create an instance of LnrpcChannelAcceptResponse', function() {
      // uncomment below and update the code to test LnrpcChannelAcceptResponse
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be.a(lnd.LnrpcChannelAcceptResponse);
    });

    it('should have the property accept (base name: "accept")', function() {
      // uncomment below and update the code to test the property accept
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property pendingChanId (base name: "pending_chan_id")', function() {
      // uncomment below and update the code to test the property pendingChanId
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property upfrontShutdown (base name: "upfront_shutdown")', function() {
      // uncomment below and update the code to test the property upfrontShutdown
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property csvDelay (base name: "csv_delay")', function() {
      // uncomment below and update the code to test the property csvDelay
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property reserveSat (base name: "reserve_sat")', function() {
      // uncomment below and update the code to test the property reserveSat
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property inFlightMaxMsat (base name: "in_flight_max_msat")', function() {
      // uncomment below and update the code to test the property inFlightMaxMsat
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property maxHtlcCount (base name: "max_htlc_count")', function() {
      // uncomment below and update the code to test the property maxHtlcCount
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property minHtlcIn (base name: "min_htlc_in")', function() {
      // uncomment below and update the code to test the property minHtlcIn
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

    it('should have the property minAcceptDepth (base name: "min_accept_depth")', function() {
      // uncomment below and update the code to test the property minAcceptDepth
      //var instance = new lnd.LnrpcChannelAcceptResponse();
      //expect(instance).to.be();
    });

  });

}));
