/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
*  - RESERVED: The numbers assigned in this enumeration match the failure codes as defined in BOLT #4. Because protobuf 3 requires enums to start with 0, a RESERVED value is added.  - INTERNAL_FAILURE: An internal error occurred.  - UNKNOWN_FAILURE: The error source is known, but the failure itself couldn't be decoded.  - UNREADABLE_FAILURE: An unreadable failure result is returned if the received failure message cannot be decrypted. In that case the error source is unknown.
*/
export type FailureFailureCode = "RESERVED" | "INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS" | "INCORRECT_PAYMENT_AMOUNT" | "FINAL_INCORRECT_CLTV_EXPIRY" | "FINAL_INCORRECT_HTLC_AMOUNT" | "FINAL_EXPIRY_TOO_SOON" | "INVALID_REALM" | "EXPIRY_TOO_SOON" | "INVALID_ONION_VERSION" | "INVALID_ONION_HMAC" | "INVALID_ONION_KEY" | "AMOUNT_BELOW_MINIMUM" | "FEE_INSUFFICIENT" | "INCORRECT_CLTV_EXPIRY" | "CHANNEL_DISABLED" | "TEMPORARY_CHANNEL_FAILURE" | "REQUIRED_NODE_FEATURE_MISSING" | "REQUIRED_CHANNEL_FEATURE_MISSING" | "UNKNOWN_NEXT_PEER" | "TEMPORARY_NODE_FAILURE" | "PERMANENT_NODE_FAILURE" | "PERMANENT_CHANNEL_FAILURE" | "EXPIRY_TOO_FAR" | "MPP_TIMEOUT" | "INVALID_ONION_PAYLOAD" | "INTERNAL_FAILURE" | "UNKNOWN_FAILURE" | "UNREADABLE_FAILURE" ;
