/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcSendCoinsRequest {
    'addr'?: string;
    'amount'?: string;
    /**
    * The target number of blocks that this transaction should be confirmed by.
    */
    'targetConf'?: number;
    /**
    * A manual fee rate set in sat/vbyte that should be used when crafting the transaction.
    */
    'satPerVbyte'?: string;
    /**
    * Deprecated, use sat_per_vbyte. A manual fee rate set in sat/vbyte that should be used when crafting the transaction.
    */
    'satPerByte'?: string;
    /**
    * If set, then the amount field will be ignored, and lnd will attempt to send all the coins under control of the internal wallet to the specified address.
    */
    'sendAll'?: boolean;
    /**
    * An optional label for the transaction, limited to 500 characters.
    */
    'label'?: string;
    /**
    * The minimum number of confirmations each one of your outputs used for the transaction must satisfy.
    */
    'minConfs'?: number;
    /**
    * Whether unconfirmed outputs should be used as inputs for the transaction.
    */
    'spendUnconfirmed'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addr",
            "baseName": "addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "targetConf",
            "baseName": "target_conf",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "satPerVbyte",
            "baseName": "sat_per_vbyte",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "satPerByte",
            "baseName": "sat_per_byte",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "sendAll",
            "baseName": "send_all",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "minConfs",
            "baseName": "min_confs",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "spendUnconfirmed",
            "baseName": "spend_unconfirmed",
            "type": "boolean",
            "format": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcSendCoinsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

