/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcChannelFeeReport } from './LnrpcChannelFeeReport';
import { HttpFile } from '../http/http';

export class LnrpcFeeReportResponse {
    /**
    * An array of channel fee reports which describes the current fee schedule for each channel.
    */
    'channelFees'?: Array<LnrpcChannelFeeReport>;
    /**
    * The total amount of fee revenue (in satoshis) the switch has collected over the past 24 hrs.
    */
    'dayFeeSum'?: string;
    /**
    * The total amount of fee revenue (in satoshis) the switch has collected over the past 1 week.
    */
    'weekFeeSum'?: string;
    /**
    * The total amount of fee revenue (in satoshis) the switch has collected over the past 1 month.
    */
    'monthFeeSum'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelFees",
            "baseName": "channel_fees",
            "type": "Array<LnrpcChannelFeeReport>",
            "format": ""
        },
        {
            "name": "dayFeeSum",
            "baseName": "day_fee_sum",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "weekFeeSum",
            "baseName": "week_fee_sum",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "monthFeeSum",
            "baseName": "month_fee_sum",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcFeeReportResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

