/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcNetworkInfo {
    'graphDiameter'?: number;
    'avgOutDegree'?: number;
    'maxOutDegree'?: number;
    'numNodes'?: number;
    'numChannels'?: number;
    'totalNetworkCapacity'?: string;
    'avgChannelSize'?: number;
    'minChannelSize'?: string;
    'maxChannelSize'?: string;
    'medianChannelSizeSat'?: string;
    /**
    * The number of edges marked as zombies.
    */
    'numZombieChans'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "graphDiameter",
            "baseName": "graph_diameter",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "avgOutDegree",
            "baseName": "avg_out_degree",
            "type": "number",
            "format": "double"
        },
        {
            "name": "maxOutDegree",
            "baseName": "max_out_degree",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numNodes",
            "baseName": "num_nodes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numChannels",
            "baseName": "num_channels",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalNetworkCapacity",
            "baseName": "total_network_capacity",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "avgChannelSize",
            "baseName": "avg_channel_size",
            "type": "number",
            "format": "double"
        },
        {
            "name": "minChannelSize",
            "baseName": "min_channel_size",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "maxChannelSize",
            "baseName": "max_channel_size",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "medianChannelSizeSat",
            "baseName": "median_channel_size_sat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "numZombieChans",
            "baseName": "num_zombie_chans",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcNetworkInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

