/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcPeer } from './LnrpcPeer';
import { HttpFile } from '../http/http';

export class LnrpcListPeersResponse {
    'peers'?: Array<LnrpcPeer>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "peers",
            "baseName": "peers",
            "type": "Array<LnrpcPeer>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcListPeersResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

