/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcNodePair {
    /**
    * The sending node of the pair. When using REST, this field must be encoded as base64.
    */
    '_from'?: string;
    /**
    * The receiving node of the pair. When using REST, this field must be encoded as base64.
    */
    'to'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_from",
            "baseName": "from",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcNodePair.attributeTypeMap;
    }

    public constructor() {
    }
}

