/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcFundingShim } from './LnrpcFundingShim';
import { HttpFile } from '../http/http';

export class LnrpcOpenChannelRequest {
    /**
    * A manual fee rate set in sat/vbyte that should be used when crafting the funding transaction.
    */
    'satPerVbyte'?: string;
    /**
    * The pubkey of the node to open a channel with. When using REST, this field must be encoded as base64.
    */
    'nodePubkey'?: string;
    /**
    * The hex encoded pubkey of the node to open a channel with. Deprecated now that the REST gateway supports base64 encoding of bytes fields.
    */
    'nodePubkeyString'?: string;
    'localFundingAmount'?: string;
    'pushSat'?: string;
    /**
    * The target number of blocks that the funding transaction should be confirmed by.
    */
    'targetConf'?: number;
    /**
    * Deprecated, use sat_per_vbyte. A manual fee rate set in sat/vbyte that should be used when crafting the funding transaction.
    */
    'satPerByte'?: string;
    /**
    * Whether this channel should be private, not announced to the greater network.
    */
    '_private'?: boolean;
    /**
    * The minimum value in millisatoshi we will require for incoming HTLCs on the channel.
    */
    'minHtlcMsat'?: string;
    /**
    * The delay we require on the remote's commitment transaction. If this is not set, it will be scaled automatically with the channel size.
    */
    'remoteCsvDelay'?: number;
    /**
    * The minimum number of confirmations each one of your outputs used for the funding transaction must satisfy.
    */
    'minConfs'?: number;
    /**
    * Whether unconfirmed outputs should be used as inputs for the funding transaction.
    */
    'spendUnconfirmed'?: boolean;
    /**
    * Close address is an optional address which specifies the address to which funds should be paid out to upon cooperative close. This field may only be set if the peer supports the option upfront feature bit (call listpeers to check). The remote peer will only accept cooperative closes to this address if it is set.  Note: If this value is set on channel creation, you will *not* be able to cooperatively close out to a different address.
    */
    'closeAddress'?: string;
    'fundingShim'?: LnrpcFundingShim;
    /**
    * The maximum amount of coins in millisatoshi that can be pending within the channel. It only applies to the remote party.
    */
    'remoteMaxValueInFlightMsat'?: string;
    /**
    * The maximum number of concurrent HTLCs we will allow the remote party to add to the commitment transaction.
    */
    'remoteMaxHtlcs'?: number;
    /**
    * Max local csv is the maximum csv delay we will allow for our own commitment transaction.
    */
    'maxLocalCsv'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "satPerVbyte",
            "baseName": "sat_per_vbyte",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "nodePubkey",
            "baseName": "node_pubkey",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "nodePubkeyString",
            "baseName": "node_pubkey_string",
            "type": "string",
            "format": ""
        },
        {
            "name": "localFundingAmount",
            "baseName": "local_funding_amount",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "pushSat",
            "baseName": "push_sat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "targetConf",
            "baseName": "target_conf",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "satPerByte",
            "baseName": "sat_per_byte",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "_private",
            "baseName": "private",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "minHtlcMsat",
            "baseName": "min_htlc_msat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "remoteCsvDelay",
            "baseName": "remote_csv_delay",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "minConfs",
            "baseName": "min_confs",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "spendUnconfirmed",
            "baseName": "spend_unconfirmed",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "closeAddress",
            "baseName": "close_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "fundingShim",
            "baseName": "funding_shim",
            "type": "LnrpcFundingShim",
            "format": ""
        },
        {
            "name": "remoteMaxValueInFlightMsat",
            "baseName": "remote_max_value_in_flight_msat",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "remoteMaxHtlcs",
            "baseName": "remote_max_htlcs",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxLocalCsv",
            "baseName": "max_local_csv",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcOpenChannelRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

