/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcEstimateFeeResponse {
    /**
    * The total fee in satoshis.
    */
    'feeSat'?: string;
    /**
    * Deprecated, use sat_per_vbyte. The fee rate in satoshi/vbyte.
    */
    'feerateSatPerByte'?: string;
    /**
    * The fee rate in satoshi/vbyte.
    */
    'satPerVbyte'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "feeSat",
            "baseName": "fee_sat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "feerateSatPerByte",
            "baseName": "feerate_sat_per_byte",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "satPerVbyte",
            "baseName": "sat_per_vbyte",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcEstimateFeeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

