/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcAmount {
    /**
    * Value denominated in satoshis.
    */
    'sat'?: string;
    /**
    * Value denominated in milli-satoshis.
    */
    'msat'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sat",
            "baseName": "sat",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "msat",
            "baseName": "msat",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcAmount.attributeTypeMap;
    }

    public constructor() {
    }
}

