/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InvoiceInvoiceState } from './InvoiceInvoiceState';
import { LnrpcFeature } from './LnrpcFeature';
import { LnrpcInvoiceHTLC } from './LnrpcInvoiceHTLC';
import { LnrpcRouteHint } from './LnrpcRouteHint';
import { HttpFile } from '../http/http';

export class LnrpcInvoice {
    /**
    * An optional memo to attach along with the invoice. Used for record keeping purposes for the invoice's creator, and will also be set in the description field of the encoded payment request if the description_hash field is not being used.
    */
    'memo'?: string;
    /**
    * The hex-encoded preimage (32 byte) which will allow settling an incoming HTLC payable to this preimage. When using REST, this field must be encoded as base64.
    */
    'rPreimage'?: string;
    /**
    * The hash of the preimage. When using REST, this field must be encoded as base64.
    */
    'rHash'?: string;
    /**
    * The fields value and value_msat are mutually exclusive.
    */
    'value'?: string;
    /**
    * The fields value and value_msat are mutually exclusive.
    */
    'valueMsat'?: string;
    'settled'?: boolean;
    'creationDate'?: string;
    'settleDate'?: string;
    /**
    * A bare-bones invoice for a payment within the Lightning Network. With the details of the invoice, the sender has all the data necessary to send a payment to the recipient.
    */
    'paymentRequest'?: string;
    /**
    * Hash (SHA-256) of a description of the payment. Used if the description of payment (memo) is too long to naturally fit within the description field of an encoded payment request. When using REST, this field must be encoded as base64.
    */
    'descriptionHash'?: string;
    /**
    * Payment request expiry time in seconds. Default is 3600 (1 hour).
    */
    'expiry'?: string;
    /**
    * Fallback on-chain address.
    */
    'fallbackAddr'?: string;
    /**
    * Delta to use for the time-lock of the CLTV extended to the final hop.
    */
    'cltvExpiry'?: string;
    /**
    * Route hints that can each be individually used to assist in reaching the invoice's destination.
    */
    'routeHints'?: Array<LnrpcRouteHint>;
    /**
    * Whether this invoice should include routing hints for private channels.
    */
    '_private'?: boolean;
    /**
    * The \"add\" index of this invoice. Each newly created invoice will increment this index making it monotonically increasing. Callers to the SubscribeInvoices call can use this to instantly get notified of all added invoices with an add_index greater than this one.
    */
    'addIndex'?: string;
    /**
    * The \"settle\" index of this invoice. Each newly settled invoice will increment this index making it monotonically increasing. Callers to the SubscribeInvoices call can use this to instantly get notified of all settled invoices with an settle_index greater than this one.
    */
    'settleIndex'?: string;
    /**
    * Deprecated, use amt_paid_sat or amt_paid_msat.
    */
    'amtPaid'?: string;
    /**
    * The amount that was accepted for this invoice, in satoshis. This will ONLY be set if this invoice has been settled. We provide this field as if the invoice was created with a zero value, then we need to record what amount was ultimately accepted. Additionally, it's possible that the sender paid MORE that was specified in the original invoice. So we'll record that here as well.
    */
    'amtPaidSat'?: string;
    /**
    * The amount that was accepted for this invoice, in millisatoshis. This will ONLY be set if this invoice has been settled. We provide this field as if the invoice was created with a zero value, then we need to record what amount was ultimately accepted. Additionally, it's possible that the sender paid MORE that was specified in the original invoice. So we'll record that here as well.
    */
    'amtPaidMsat'?: string;
    'state'?: InvoiceInvoiceState;
    /**
    * List of HTLCs paying to this invoice [EXPERIMENTAL].
    */
    'htlcs'?: Array<LnrpcInvoiceHTLC>;
    /**
    * List of features advertised on the invoice.
    */
    'features'?: { [key: string]: LnrpcFeature; };
    /**
    * Indicates if this invoice was a spontaneous payment that arrived via keysend [EXPERIMENTAL].
    */
    'isKeysend'?: boolean;
    /**
    * The payment address of this invoice. This value will be used in MPP payments, and also for newer invoies that always require the MPP paylaod for added end-to-end security.
    */
    'paymentAddr'?: string;
    /**
    * Signals whether or not this is an AMP invoice.
    */
    'isAmp'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string",
            "format": ""
        },
        {
            "name": "rPreimage",
            "baseName": "r_preimage",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "rHash",
            "baseName": "r_hash",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "valueMsat",
            "baseName": "value_msat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "settled",
            "baseName": "settled",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "creationDate",
            "baseName": "creation_date",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "settleDate",
            "baseName": "settle_date",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "paymentRequest",
            "baseName": "payment_request",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionHash",
            "baseName": "description_hash",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "expiry",
            "baseName": "expiry",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "fallbackAddr",
            "baseName": "fallback_addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "cltvExpiry",
            "baseName": "cltv_expiry",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "routeHints",
            "baseName": "route_hints",
            "type": "Array<LnrpcRouteHint>",
            "format": ""
        },
        {
            "name": "_private",
            "baseName": "private",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "addIndex",
            "baseName": "add_index",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "settleIndex",
            "baseName": "settle_index",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "amtPaid",
            "baseName": "amt_paid",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "amtPaidSat",
            "baseName": "amt_paid_sat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "amtPaidMsat",
            "baseName": "amt_paid_msat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "InvoiceInvoiceState",
            "format": ""
        },
        {
            "name": "htlcs",
            "baseName": "htlcs",
            "type": "Array<LnrpcInvoiceHTLC>",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "{ [key: string]: LnrpcFeature; }",
            "format": ""
        },
        {
            "name": "isKeysend",
            "baseName": "is_keysend",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "paymentAddr",
            "baseName": "payment_addr",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "isAmp",
            "baseName": "is_amp",
            "type": "boolean",
            "format": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcInvoice.attributeTypeMap;
    }

    public constructor() {
    }
}

