/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcKeyLocator {
    /**
    * The family of key being identified.
    */
    'keyFamily'?: number;
    /**
    * The precise index of the key being identified.
    */
    'keyIndex'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyFamily",
            "baseName": "key_family",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "keyIndex",
            "baseName": "key_index",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcKeyLocator.attributeTypeMap;
    }

    public constructor() {
    }
}

