/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcTransaction } from './LnrpcTransaction';
import { HttpFile } from '../http/http';

export class LnrpcTransactionDetails {
    /**
    * The list of transactions relevant to the wallet.
    */
    'transactions'?: Array<LnrpcTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<LnrpcTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcTransactionDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

