/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcChannelBackups } from './LnrpcChannelBackups';
import { HttpFile } from '../http/http';

export class LnrpcRestoreChanBackupRequest {
    'chanBackups'?: LnrpcChannelBackups;
    /**
    * The channels to restore in the packed multi backup format. When using REST, this field must be encoded as base64.
    */
    'multiChanBackup'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chanBackups",
            "baseName": "chan_backups",
            "type": "LnrpcChannelBackups",
            "format": ""
        },
        {
            "name": "multiChanBackup",
            "baseName": "multi_chan_backup",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcRestoreChanBackupRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

