/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcChannelPoint {
    /**
    * Txid of the funding transaction. When using REST, this field must be encoded as base64.
    */
    'fundingTxidBytes'?: string;
    /**
    * Hex-encoded string representing the byte-reversed hash of the funding transaction.
    */
    'fundingTxidStr'?: string;
    'outputIndex'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fundingTxidBytes",
            "baseName": "funding_txid_bytes",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "fundingTxidStr",
            "baseName": "funding_txid_str",
            "type": "string",
            "format": ""
        },
        {
            "name": "outputIndex",
            "baseName": "output_index",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcChannelPoint.attributeTypeMap;
    }

    public constructor() {
    }
}

