/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcChannel } from './LnrpcChannel';
import { HttpFile } from '../http/http';

export class LnrpcListChannelsResponse {
    'channels'?: Array<LnrpcChannel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channels",
            "baseName": "channels",
            "type": "Array<LnrpcChannel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcListChannelsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

