/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcTransaction {
    'txHash'?: string;
    'amount'?: string;
    'numConfirmations'?: number;
    'blockHash'?: string;
    'blockHeight'?: number;
    'timeStamp'?: string;
    'totalFees'?: string;
    'destAddresses'?: Array<string>;
    /**
    * The raw transaction hex.
    */
    'rawTxHex'?: string;
    /**
    * A label that was optionally set on transaction broadcast.
    */
    'label'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "txHash",
            "baseName": "tx_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "numConfirmations",
            "baseName": "num_confirmations",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "blockHash",
            "baseName": "block_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "blockHeight",
            "baseName": "block_height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timeStamp",
            "baseName": "time_stamp",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "totalFees",
            "baseName": "total_fees",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "destAddresses",
            "baseName": "dest_addresses",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "rawTxHex",
            "baseName": "raw_tx_hex",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}

