/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcMPPRecord {
    /**
    * A unique, random identifier used to authenticate the sender as the intended payer of a multi-path payment. The payment_addr must be the same for all subpayments, and match the payment_addr provided in the receiver's invoice. The same payment_addr must be used on all subpayments.
    */
    'paymentAddr'?: string;
    /**
    * The total amount in milli-satoshis being sent as part of a larger multi-path payment. The caller is responsible for ensuring subpayments to the same node and payment_hash sum exactly to total_amt_msat. The same total_amt_msat must be used on all subpayments.
    */
    'totalAmtMsat'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentAddr",
            "baseName": "payment_addr",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "totalAmtMsat",
            "baseName": "total_amt_msat",
            "type": "string",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcMPPRecord.attributeTypeMap;
    }

    public constructor() {
    }
}

