/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcMacaroonPermission } from './LnrpcMacaroonPermission';
import { HttpFile } from '../http/http';

export class LnrpcBakeMacaroonRequest {
    /**
    * The list of permissions the new macaroon should grant.
    */
    'permissions'?: Array<LnrpcMacaroonPermission>;
    /**
    * The root key ID used to create the macaroon, must be a positive integer.
    */
    'rootKeyId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<LnrpcMacaroonPermission>",
            "format": ""
        },
        {
            "name": "rootKeyId",
            "baseName": "root_key_id",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcBakeMacaroonRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

