/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcChain } from './LnrpcChain';
import { LnrpcFeature } from './LnrpcFeature';
import { HttpFile } from '../http/http';

export class LnrpcGetInfoResponse {
    /**
    * The version of the LND software that the node is running.
    */
    'version'?: string;
    /**
    * The SHA1 commit hash that the daemon is compiled with.
    */
    'commitHash'?: string;
    /**
    * The identity pubkey of the current node.
    */
    'identityPubkey'?: string;
    'alias'?: string;
    'color'?: string;
    'numPendingChannels'?: number;
    'numActiveChannels'?: number;
    'numInactiveChannels'?: number;
    'numPeers'?: number;
    'blockHeight'?: number;
    'blockHash'?: string;
    'bestHeaderTimestamp'?: string;
    'syncedToChain'?: boolean;
    /**
    * Whether we consider ourselves synced with the public channel graph.
    */
    'syncedToGraph'?: boolean;
    'testnet'?: boolean;
    'chains'?: Array<LnrpcChain>;
    /**
    * The URIs of the current node.
    */
    'uris'?: Array<string>;
    /**
    * Features that our node has advertised in our init message, node announcements and invoices.
    */
    'features'?: { [key: string]: LnrpcFeature; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "commitHash",
            "baseName": "commit_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "identityPubkey",
            "baseName": "identity_pubkey",
            "type": "string",
            "format": ""
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "numPendingChannels",
            "baseName": "num_pending_channels",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numActiveChannels",
            "baseName": "num_active_channels",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numInactiveChannels",
            "baseName": "num_inactive_channels",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numPeers",
            "baseName": "num_peers",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "blockHeight",
            "baseName": "block_height",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "blockHash",
            "baseName": "block_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "bestHeaderTimestamp",
            "baseName": "best_header_timestamp",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "syncedToChain",
            "baseName": "synced_to_chain",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "syncedToGraph",
            "baseName": "synced_to_graph",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "testnet",
            "baseName": "testnet",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "chains",
            "baseName": "chains",
            "type": "Array<LnrpcChain>",
            "format": ""
        },
        {
            "name": "uris",
            "baseName": "uris",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "{ [key: string]: LnrpcFeature; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcGetInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

