/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcRoute } from './LnrpcRoute';
import { HttpFile } from '../http/http';

export class LnrpcQueryRoutesResponse {
    /**
    * The route that results from the path finding operation. This is still a repeated field to retain backwards compatibility.
    */
    'routes'?: Array<LnrpcRoute>;
    'successProb'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "routes",
            "baseName": "routes",
            "type": "Array<LnrpcRoute>",
            "format": ""
        },
        {
            "name": "successProb",
            "baseName": "success_prob",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcQueryRoutesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

