/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcLightningAddress } from './LnrpcLightningAddress';
import { HttpFile } from '../http/http';

export class LnrpcConnectPeerRequest {
    'addr'?: LnrpcLightningAddress;
    /**
    * If set, the daemon will attempt to persistently connect to the target peer. Otherwise, the call will be synchronous.
    */
    'perm'?: boolean;
    /**
    * The connection timeout value (in seconds) for this request. It won't affect other requests.
    */
    'timeout'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addr",
            "baseName": "addr",
            "type": "LnrpcLightningAddress",
            "format": ""
        },
        {
            "name": "perm",
            "baseName": "perm",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcConnectPeerRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

