/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcUtxo } from './LnrpcUtxo';
import { HttpFile } from '../http/http';

export class LnrpcListUnspentResponse {
    'utxos'?: Array<LnrpcUtxo>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "utxos",
            "baseName": "utxos",
            "type": "Array<LnrpcUtxo>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcListUnspentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

