/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcFeature } from './LnrpcFeature';
import { LnrpcNodeAddress } from './LnrpcNodeAddress';
import { HttpFile } from '../http/http';

export class LnrpcNodeUpdate {
    /**
    * Deprecated, use node_addresses.
    */
    'addresses'?: Array<string>;
    'identityKey'?: string;
    /**
    * Deprecated, use features.
    */
    'globalFeatures'?: string;
    'alias'?: string;
    'color'?: string;
    'nodeAddresses'?: Array<LnrpcNodeAddress>;
    /**
    * Features that the node has advertised in the init message, node announcements and invoices.
    */
    'features'?: { [key: string]: LnrpcFeature; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "identityKey",
            "baseName": "identity_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "globalFeatures",
            "baseName": "global_features",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "nodeAddresses",
            "baseName": "node_addresses",
            "type": "Array<LnrpcNodeAddress>",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "{ [key: string]: LnrpcFeature; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcNodeUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

