/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FailureFailureCode } from './FailureFailureCode';
import { LnrpcChannelUpdate } from './LnrpcChannelUpdate';
import { HttpFile } from '../http/http';

export class LnrpcFailure {
    'code'?: FailureFailureCode;
    'channelUpdate'?: LnrpcChannelUpdate;
    /**
    * A failure type-dependent htlc value.
    */
    'htlcMsat'?: string;
    /**
    * The sha256 sum of the onion payload.
    */
    'onionSha256'?: string;
    /**
    * A failure type-dependent cltv expiry value.
    */
    'cltvExpiry'?: number;
    /**
    * A failure type-dependent flags value.
    */
    'flags'?: number;
    /**
    * The position in the path of the intermediate or final node that generated the failure message. Position zero is the sender node.
    */
    'failureSourceIndex'?: number;
    /**
    * A failure type-dependent block height.
    */
    'height'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "FailureFailureCode",
            "format": ""
        },
        {
            "name": "channelUpdate",
            "baseName": "channel_update",
            "type": "LnrpcChannelUpdate",
            "format": ""
        },
        {
            "name": "htlcMsat",
            "baseName": "htlc_msat",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "onionSha256",
            "baseName": "onion_sha_256",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "cltvExpiry",
            "baseName": "cltv_expiry",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "failureSourceIndex",
            "baseName": "failure_source_index",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcFailure.attributeTypeMap;
    }

    public constructor() {
    }
}

