/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LnrpcPendingHTLC {
    'incoming'?: boolean;
    'amount'?: string;
    'outpoint'?: string;
    'maturityHeight'?: number;
    /**
    * The number of blocks remaining until the current stage can be swept. Negative values indicate how many blocks have passed since becoming mature.
    */
    'blocksTilMaturity'?: number;
    'stage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "incoming",
            "baseName": "incoming",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "outpoint",
            "baseName": "outpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "maturityHeight",
            "baseName": "maturity_height",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "blocksTilMaturity",
            "baseName": "blocks_til_maturity",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "stage",
            "baseName": "stage",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcPendingHTLC.attributeTypeMap;
    }

    public constructor() {
    }
}

