/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcChannelPoint } from './LnrpcChannelPoint';
import { LnrpcRoutingPolicy } from './LnrpcRoutingPolicy';
import { HttpFile } from '../http/http';

export class LnrpcChannelEdgeUpdate {
    /**
    * The unique channel ID for the channel. The first 3 bytes are the block height, the next 3 the index within the block, and the last 2 bytes are the output index for the channel.
    */
    'chanId'?: string;
    'chanPoint'?: LnrpcChannelPoint;
    'capacity'?: string;
    'routingPolicy'?: LnrpcRoutingPolicy;
    'advertisingNode'?: string;
    'connectingNode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chanId",
            "baseName": "chan_id",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "chanPoint",
            "baseName": "chan_point",
            "type": "LnrpcChannelPoint",
            "format": ""
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "routingPolicy",
            "baseName": "routing_policy",
            "type": "LnrpcRoutingPolicy",
            "format": ""
        },
        {
            "name": "advertisingNode",
            "baseName": "advertising_node",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectingNode",
            "baseName": "connecting_node",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcChannelEdgeUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

