/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcChannelPoint } from './LnrpcChannelPoint';
import { HttpFile } from '../http/http';

export class LnrpcChannelBackup {
    'chanPoint'?: LnrpcChannelPoint;
    /**
    * Is an encrypted single-chan backup. this can be passed to RestoreChannelBackups, or the WalletUnlocker Init and Unlock methods in order to trigger the recovery protocol. When using REST, this field must be encoded as base64.
    */
    'chanBackup'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chanPoint",
            "baseName": "chan_point",
            "type": "LnrpcChannelPoint",
            "format": ""
        },
        {
            "name": "chanBackup",
            "baseName": "chan_backup",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcChannelBackup.attributeTypeMap;
    }

    public constructor() {
    }
}

