/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcAddressType } from './LnrpcAddressType';
import { LnrpcOutPoint } from './LnrpcOutPoint';
import { HttpFile } from '../http/http';

export class LnrpcUtxo {
    'addressType'?: LnrpcAddressType;
    'address'?: string;
    'amountSat'?: string;
    'pkScript'?: string;
    'outpoint'?: LnrpcOutPoint;
    'confirmations'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addressType",
            "baseName": "address_type",
            "type": "LnrpcAddressType",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountSat",
            "baseName": "amount_sat",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "pkScript",
            "baseName": "pk_script",
            "type": "string",
            "format": ""
        },
        {
            "name": "outpoint",
            "baseName": "outpoint",
            "type": "LnrpcOutPoint",
            "format": ""
        },
        {
            "name": "confirmations",
            "baseName": "confirmations",
            "type": "string",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcUtxo.attributeTypeMap;
    }

    public constructor() {
    }
}

