/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcRoute } from './LnrpcRoute';
import { HttpFile } from '../http/http';

export class LnrpcSendResponse {
    'paymentError'?: string;
    'paymentPreimage'?: string;
    'paymentRoute'?: LnrpcRoute;
    'paymentHash'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentError",
            "baseName": "payment_error",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentPreimage",
            "baseName": "payment_preimage",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "paymentRoute",
            "baseName": "payment_route",
            "type": "LnrpcRoute",
            "format": ""
        },
        {
            "name": "paymentHash",
            "baseName": "payment_hash",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return LnrpcSendResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

