/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LnrpcMacaroonPermissionList } from './LnrpcMacaroonPermissionList';
import { HttpFile } from '../http/http';

export class LnrpcListPermissionsResponse {
    /**
    * A map between all RPC method URIs and their required macaroon permissions to access them.
    */
    'methodPermissions'?: { [key: string]: LnrpcMacaroonPermissionList; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "methodPermissions",
            "baseName": "method_permissions",
            "type": "{ [key: string]: LnrpcMacaroonPermissionList; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LnrpcListPermissionsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

