/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
*  - UNKNOWN_SYNC: Denotes that we cannot determine the peer's current sync type.  - ACTIVE_SYNC: Denotes that we are actively receiving new graph updates from the peer.  - PASSIVE_SYNC: Denotes that we are not receiving new graph updates from the peer.  - PINNED_SYNC: Denotes that this peer is pinned into an active sync.
*/
export type PeerSyncType = "UNKNOWN_SYNC" | "ACTIVE_SYNC" | "PASSIVE_SYNC" | "PINNED_SYNC" ;
