/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ForceClosedChannelAnchorState } from './ForceClosedChannelAnchorState';
import { LnrpcPendingHTLC } from './LnrpcPendingHTLC';
import { PendingChannelsResponsePendingChannel } from './PendingChannelsResponsePendingChannel';
import { HttpFile } from '../http/http';

export class PendingChannelsResponseForceClosedChannel {
    'channel'?: PendingChannelsResponsePendingChannel;
    'closingTxid'?: string;
    'limboBalance'?: string;
    'maturityHeight'?: number;
    /**
    * Remaining # of blocks until the commitment output can be swept. Negative values indicate how many blocks have passed since becoming mature.
    */
    'blocksTilMaturity'?: number;
    'recoveredBalance'?: string;
    'pendingHtlcs'?: Array<LnrpcPendingHTLC>;
    'anchor'?: ForceClosedChannelAnchorState;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "PendingChannelsResponsePendingChannel",
            "format": ""
        },
        {
            "name": "closingTxid",
            "baseName": "closing_txid",
            "type": "string",
            "format": ""
        },
        {
            "name": "limboBalance",
            "baseName": "limbo_balance",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "maturityHeight",
            "baseName": "maturity_height",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "blocksTilMaturity",
            "baseName": "blocks_til_maturity",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "recoveredBalance",
            "baseName": "recovered_balance",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "pendingHtlcs",
            "baseName": "pending_htlcs",
            "type": "Array<LnrpcPendingHTLC>",
            "format": ""
        },
        {
            "name": "anchor",
            "baseName": "anchor",
            "type": "ForceClosedChannelAnchorState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PendingChannelsResponseForceClosedChannel.attributeTypeMap;
    }

    public constructor() {
    }
}

