/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PendingChannelsResponseCommitments } from './PendingChannelsResponseCommitments';
import { PendingChannelsResponsePendingChannel } from './PendingChannelsResponsePendingChannel';
import { HttpFile } from '../http/http';

export class PendingChannelsResponseWaitingCloseChannel {
    'channel'?: PendingChannelsResponsePendingChannel;
    'limboBalance'?: string;
    'commitments'?: PendingChannelsResponseCommitments;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "PendingChannelsResponsePendingChannel",
            "format": ""
        },
        {
            "name": "limboBalance",
            "baseName": "limbo_balance",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "commitments",
            "baseName": "commitments",
            "type": "PendingChannelsResponseCommitments",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PendingChannelsResponseWaitingCloseChannel.attributeTypeMap;
    }

    public constructor() {
    }
}

