/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PendingChannelsResponseCommitments {
    /**
    * Hash of the local version of the commitment tx.
    */
    'localTxid'?: string;
    /**
    * Hash of the remote version of the commitment tx.
    */
    'remoteTxid'?: string;
    /**
    * Hash of the remote pending version of the commitment tx.
    */
    'remotePendingTxid'?: string;
    /**
    * The amount in satoshis calculated to be paid in fees for the local commitment.
    */
    'localCommitFeeSat'?: string;
    /**
    * The amount in satoshis calculated to be paid in fees for the remote commitment.
    */
    'remoteCommitFeeSat'?: string;
    /**
    * The amount in satoshis calculated to be paid in fees for the remote pending commitment.
    */
    'remotePendingCommitFeeSat'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "localTxid",
            "baseName": "local_txid",
            "type": "string",
            "format": ""
        },
        {
            "name": "remoteTxid",
            "baseName": "remote_txid",
            "type": "string",
            "format": ""
        },
        {
            "name": "remotePendingTxid",
            "baseName": "remote_pending_txid",
            "type": "string",
            "format": ""
        },
        {
            "name": "localCommitFeeSat",
            "baseName": "local_commit_fee_sat",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "remoteCommitFeeSat",
            "baseName": "remote_commit_fee_sat",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "remotePendingCommitFeeSat",
            "baseName": "remote_pending_commit_fee_sat",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return PendingChannelsResponseCommitments.attributeTypeMap;
    }

    public constructor() {
    }
}

