/**
 * rpc.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProtobufAny } from './ProtobufAny';
import { HttpFile } from '../http/http';

export class RuntimeStreamError {
    'grpcCode'?: number;
    'httpCode'?: number;
    'message'?: string;
    'httpStatus'?: string;
    'details'?: Array<ProtobufAny>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "grpcCode",
            "baseName": "grpc_code",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "httpCode",
            "baseName": "http_code",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "httpStatus",
            "baseName": "http_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "Array<ProtobufAny>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RuntimeStreamError.attributeTypeMap;
    }

    public constructor() {
    }
}

